import type { Metadata } from "next";
import { CloneAppTemplate, type CloneAppTemplateConfig } from "../../components/solutions/CloneAppTemplate";

export const metadata: Metadata = {
  title: "Gym & Fitness App Development Dubai | Webtek Digital",
  description:
    "Build a custom gym and fitness app in Dubai with membership, class booking, trainer and admin solutions developed by Webtek Digital.",
};

const config: CloneAppTemplateConfig = {
  eyebrow: "Custom fitness platforms",
  title: "Gym & Fitness App Development in Dubai",
  lead: "Build a branded fitness experience with membership management, class booking, workout plans and trainer tools designed for members and staff. Whether you operate a single gym, a multi-branch chain, a boutique studio or a digital fitness brand, we create a tailored solution that connects customers, coaches, locations, payments and business operations.",
  primaryCta: "Discuss Your App",
  secondaryCta: "Explore the Platform",
  heroImage: "/solutions/gym/Gym_Fitness_App_User_Tracking_Workout.png",
  heroImageAlt: "Gym and fitness app development solution for membership and training businesses in Dubai",
  overview: [
    "A professional fitness platform connects members, trainers, classes, programmes, payments and gym operations through one reliable system. Members receive a simple way to join, book and follow plans, trainers gain organised coaching tools, and administrators maintain visibility across memberships, attendance, capacity, revenue and engagement.",
    "Webtek Digital develops every component around your operating model, locations, services, staffing structure, membership rules and brand experience. The platform can support membership gyms, pay-per-class studios, personal training, online coaching, corporate wellness, hybrid memberships or a fitness marketplace.",
  ],
  metrics: [
    ["3+", "connected member, trainer and administration experiences"],
    ["1", "central system for memberships, bookings and payments"],
    ["24/7", "access to schedules, plans and account information"],
  ],
  features: [
    ["Membership management", "Help customers compare plans, join, renew and manage access, with configurable contracts, trials, branch entitlements, freezes, reminders, invoices and receipts."],
    ["Class booking", "Provide real-time timetables, capacity, booking, cancellation, rescheduling, waitlists, reminders and attendance records around each branch and membership category."],
    ["Workout plans", "Deliver trainer-assigned programmes with exercises, instructions, media, sets, repetitions, timing, recovery guidance, session history and adherence tracking."],
    ["Trainer tools", "Give coaches role-based access to availability, calendars, assigned members, programme creation, session notes, check-ins, communication and performance feedback."],
    ["Personal training", "Manage packages, trainer allocation, appointment booking, expiry, usage balances, rescheduling, attendance and payment status."],
    ["Business analytics", "Monitor active memberships, renewals, attendance, class utilisation, trainer capacity, personal-training usage, revenue, cancellations and engagement."],
  ],
  modules: [
    {
      number: "01",
      label: "Member app",
      title: "Everything members need in one place.",
      text: "Give members one convenient place to manage membership, discover branches and trainers, book classes or personal training, follow workout plans, make payments, view receipts, join challenges and receive updates. The experience can support iOS, Android, responsive web, English and Arabic.",
      image: "/solutions/gym/Gym_Membership_App_UI_UX_Mobile_Experience.png",
      alt: "Gym member using a mobile fitness app for workouts and membership services",
    },
    {
      number: "02",
      label: "Trainer app or portal",
      title: "Keep coaching organised and personal.",
      text: "Turn schedules, member assignments and programme delivery into one structured workflow. Coaches can manage availability, review sessions, build workouts, record attendance and notes, track approved check-ins and communicate with assigned clients under appropriate permissions.",
      image: "/solutions/gym/Online_Fitness_Coaching_App_Personal_Trainer_Session.png",
      alt: "Member attending an online personal training session through a fitness app",
    },
    {
      number: "03",
      label: "Branch operations portal",
      title: "Coordinate people, classes and facilities.",
      text: "Give branch managers role-based control over local timetables, room allocation, trainer cover, attendance, capacity, package usage, front-desk check-in, facility issues, promotions and branch performance while central leadership retains group oversight.",
      image: "/solutions/gym/Gym_Management_Dashboard_UI_UX_Analytics.png",
      alt: "Gym branch manager reviewing schedules, membership activity and analytics",
    },
    {
      number: "04",
      label: "Admin dashboard",
      title: "Manage the business from one dashboard.",
      text: "Maintain central control over members, trainers, branches, plans, entitlements, class capacity, workout content, check-ins, payments, recurring billing, offers, support, corporate accounts, permissions, analytics, integrations and audit history.",
      image: "/solutions/gym/Gym_Management_Dashboard_UI_UX_Analytics.png",
      alt: "Gym administration dashboard for memberships, attendance and business analytics",
    },
  ],
  technologyLead: "A gym and fitness platform must coordinate memberships, schedules, payments, content, check-ins and user activity reliably across devices and locations. We select the architecture according to expected usage, media requirements, integration needs, privacy considerations and the long-term product roadmap.",
  technologyImage: "/solutions/gym/Gym_Fitness_App_Technology_Cloud_Security_Integrations.png",
  technologyImageAlt: "Gym and fitness app technology with cloud security and platform integrations",
  technologyTags: [
    "Flutter or React Native",
    "Swift and Kotlin",
    "React and Next.js",
    "Node.js, Laravel or Python",
    "REST or GraphQL APIs",
    "PostgreSQL, MySQL or MongoDB",
    "Secure media delivery",
    "AWS, Google Cloud or Azure",
    "Payment gateways",
    "Access-control integrations",
    "CRM and membership systems",
    "Wearable platform connections",
    "Analytics and monitoring",
  ],
  process: [
    ["Discovery", "Define the business model, member audiences, locations, services, membership rules, classes, trainer structure, payments and commercial objectives."],
    ["Research and planning", "Evaluate member expectations, staff workflows, market conventions, operational dependencies and technical constraints before prioritising the roadmap."],
    ["UX and UI design", "Map journeys for members, trainers, branch teams and administrators, then create an approved design system and interactive prototype."],
    ["Technical development", "Build the agreed mobile apps, responsive web experience, trainer tools, branch portal, administration dashboard, APIs and databases."],
    ["Content and integrations", "Configure approved workout content and connect required payment, access, communication, analytics and business systems."],
    ["Quality assurance", "Test usability, media, payments, bookings, access controls, APIs and performance across supported devices, browsers and operating systems."],
    ["Testing and launch", "Prepare production environments, app listings, analytics events, support processes and release settings for launch."],
    ["Ongoing support", "Support monitoring, issue resolution, security and dependency updates, operating-system compatibility, reporting and future enhancements."],
  ],
  detailSections: [
    {
      eyebrow: "Advanced capabilities",
      title: "More than a membership and booking application.",
      intro: "Advanced functionality can improve member engagement, coaching delivery, revenue diversification and multi-location control. Features can be included in the first release or planned as future phases.",
      items: [
        ["Digital check-in", "Use QR codes, digital membership cards or compatible access integrations to validate eligible members."],
        ["Waitlists and capacity", "Manage demand through limits, booking windows, eligibility, automatic waitlist promotion and no-show policies."],
        ["Challenges and community", "Create participation challenges, milestones, team events, community posts or leaderboards where suitable."],
        ["Loyalty and referrals", "Support retention and acquisition through points, credit, referral codes, vouchers, rewards or partner benefits."],
        ["Corporate wellness", "Manage employee invitations, eligibility, packages, programme access, utilisation reports and account billing."],
        ["Nutrition and lifestyle", "Provide professionally reviewed educational content and habit resources without presenting general information as medical treatment."],
        ["Progress check-ins", "Record authorised measurements, photographs, goals and trainer observations with consent and appropriate privacy controls."],
        ["Wearable connections", "Import selected user-authorised activity data where supported by the provider, device and permissions."],
        ["On-demand workouts", "Offer a controlled library of recorded classes, demonstrations and programmes for flexible training."],
        ["Live digital classes", "Deliver remote group or individual sessions through suitable video services with reminders, access rules and attendance."],
        ["Multi-branch memberships", "Configure plans for selected or all locations with branch-level booking, check-in and reporting."],
        ["Franchise management", "Separate data and permissions by franchise, partner or location while retaining approved group oversight."],
        ["AI-assisted features", "Consider carefully reviewed content search, programme administration or member-support automation without unsupervised medical decisions or unsupported claims."],
      ],
    },
    {
      eyebrow: "Business benefits",
      title: "Create a stronger member and fitness experience.",
      intro: "A purpose-built platform creates one clear journey from enquiry to renewal and makes daily operations easier to coordinate. Technology supports the experience but does not replace qualified coaching, safe programming, good facilities or consistent member care.",
      items: [
        ["Increase conversion", "Use clear plans, digital registration, convenient payments, trial options and visible services to reduce joining friction."],
        ["Improve convenience", "Give members one place to manage access, bookings, programmes, payments, updates and support."],
        ["Strengthen retention", "Use renewal reminders, programmes, class discovery, challenges, check-ins and communication to support participation."],
        ["Optimise class capacity", "Use live availability, waitlists, attendance and no-show information to improve timetable decisions."],
        ["Grow personal training", "Create a clearer paid-coaching journey through trainer discovery, bookings, package balances and follow-up tools."],
        ["Reduce administration", "Automate confirmations, membership records, booking rules, payment status and reporting."],
        ["Improve trainer productivity", "Organise calendars, member information, programmes and session notes for more consistent preparation and follow-up."],
        ["Gain business visibility", "Review membership activity, revenue, demand, trainer capacity, branch performance and engagement trends."],
        ["Own customer relationships", "Maintain greater control over member communication, services, offers and first-party operational data."],
        ["Scale with control", "Add locations, trainers, classes, memberships, corporate accounts and integrations through structured permissions."],
      ],
    },
    {
      eyebrow: "Industries and use cases",
      title: "Flexible fitness solutions for different businesses.",
      intro: "The platform can be configured around different membership models, facilities, service structures, professional requirements and target audiences.",
      items: [
        ["Independent gyms", "Manage memberships, classes, trainers, payments, check-ins and communication in one branded platform."],
        ["Multi-branch chains", "Coordinate plans, access rules, timetables, staff and reporting while retaining branch-level controls."],
        ["Boutique studios", "Support class-led yoga, Pilates, cycling, barre, dance and functional fitness businesses."],
        ["Personal training", "Manage consultations, packages, appointments, programmes, check-ins and trainer-client communication."],
        ["Online fitness brands", "Sell memberships, programmes, video libraries, live sessions, challenges and community access."],
        ["Women-only centres", "Create appropriate member, privacy, trainer and branch journeys for women-focused facilities."],
        ["Hotel and residential gyms", "Manage eligibility, classes, facility information and approved services across properties."],
        ["Corporate wellness", "Provide employee access, challenges, booking, communications and organisation-level utilisation reports."],
        ["Sports academies", "Coordinate athlete groups, coaching schedules, programmes, attendance and approved performance information."],
        ["Martial arts", "Manage class levels, memberships, instructors, attendance, grading information and events."],
        ["Mind-body studios", "Combine class booking, packs, memberships, instructor profiles, content and member communication."],
        ["Community facilities", "Support membership eligibility, schedules, activities and community announcements."],
        ["Fitness marketplaces", "Connect customers with approved trainers, studios or programmes through managed listings, bookings and payments."],
        ["Specialist wellness", "Develop carefully governed booking and programme tools for qualified providers, subject to professional and privacy requirements."],
      ],
    },
    {
      eyebrow: "Why Webtek Digital",
      title: "Built around your fitness model—not a generic template.",
      intro: "We connect product strategy, user experience, engineering and digital growth so the platform reflects both member needs and day-to-day fitness operations.",
      items: [
        ["Custom development", "Tailor the platform to your memberships, classes, coaching, locations, commercial model and brand."],
        ["Complete user ecosystem", "Develop member apps, trainer tools, branch portals, administration systems, APIs and marketing websites."],
        ["Marketing-first thinking", "Consider membership discovery, conversion, CRM integration, referrals, retention and analytics during planning."],
        ["UAE and GCC relevance", "Plan for Arabic interfaces, regional payments, multi-branch operations and local member expectations."],
        ["Scalable architecture", "Structure the solution for additional users, trainers, locations, classes, services, markets and integrations."],
        ["UX-focused design", "Plan each interface around practical tasks, from joining and booking to reviewing branch activity."],
        ["Transparent delivery", "Document requirements, deliverables, responsibilities, reviews and change requests throughout development."],
        ["Quality assurance", "Review membership, booking, workout, payment, check-in, reporting and administration journeys before release."],
        ["End-to-end capability", "Support strategy, branding, UI/UX, development, integrations, analytics, launch, marketing and maintenance."],
      ],
    },
    {
      eyebrow: "Project investment",
      title: "How much does a gym and fitness app cost?",
      intro: "Cost depends on the operating model, number of interfaces and complexity of the required features. After an initial consultation, we recommend an appropriate first-release scope and provide a tailored proposal rather than forcing different fitness businesses into fixed packages.",
      items: [
        ["Applications and platforms", "Scope varies according to member, trainer, branch and admin interfaces across iOS, Android and responsive web."],
        ["Membership and booking", "Plans, recurring billing, timetables, capacity, waitlists and personal-training packages shape the investment."],
        ["Content and access", "Workout media, digital check-in, access control, languages and accessibility affect design and engineering scope."],
        ["Business structure", "Corporate wellness, commissions, multi-branch operations and franchise controls introduce different requirements."],
        ["Integrations and operations", "Wearables, CRM, migration, analytics, security, testing, launch and support are assessed during discovery."],
      ],
    },
    {
      eyebrow: "Free consultation",
      title: "Let’s discuss what you want to build.",
      intro: "Speak with Webtek Digital about your fitness concept, audiences, locations, services and commercial objectives. The initial consultation helps define the required interfaces, first-release priorities and delivery approach.",
      items: [
        ["Business model", "Discuss target members, operating markets, locations, facilities, memberships and commercial goals."],
        ["Fitness services", "Review class formats, trainer requirements, workout content, personal training and programme delivery."],
        ["Access and commerce", "Define check-in, payments, packages, recurring billing, corporate accounts and permissions."],
        ["Technical scope", "Identify required applications, portals, migration, integrations, privacy needs, launch priorities and next steps."],
      ],
    },
  ],
  faqTitle: "Gym & Fitness App Development FAQs",
  faqs: [
    ["What is a gym and fitness app?", "A gym and fitness app helps members manage memberships, book classes or training, access workout content and communicate with a fitness business. A complete solution can also include trainer, branch and administration tools."],
    ["Can Webtek Digital build a custom gym app in Dubai?", "Yes. We can develop a custom gym and fitness platform for businesses in Dubai and across the UAE, tailored to memberships, bookings, programmes, locations, payments and integrations."],
    ["Which applications and portals are included?", "A solution may include a member mobile app, responsive member website, trainer app or portal, branch operations portal, administration dashboard and marketing website. The final combination is confirmed after discovery."],
    ["Can the platform manage memberships and renewals?", "Yes. It can support membership plans, trials, joining, recurring or manual payments, expiry reminders, renewals, freezes, plan changes and branch entitlements according to approved rules."],
    ["Can members book classes and join waitlists?", "Yes. Members can review schedules, capacity and instructor information, book or cancel eligible classes and join waitlists. Automatic place release and no-show policies can also be configured."],
    ["Can trainers create workout plans?", "Yes. Approved trainers can create or assign programmes using exercises, instructions, media, sets, repetitions, timing, rest and scheduling, subject to role and publishing permissions."],
    ["Can personal training sessions and packages be managed?", "Yes. The platform can support trainer availability, appointment booking, package purchase, session balance, expiry, attendance, notes and payment status."],
    ["Can the app support multiple gym branches?", "Yes. Membership access, schedules, trainers, facilities, check-ins and reporting can be managed by branch while central administrators retain group-level oversight."],
    ["Can members check in using the app?", "Potentially. QR codes, digital membership cards or compatible access integrations can validate eligible members. Feasibility depends on the chosen hardware or provider."],
    ["Can wearable devices be connected?", "Potentially. Selected wearable or health platforms may provide APIs for user-authorised activity data. Availability, accuracy and permitted use depend on the provider, device, region and permissions."],
    ["Can the application support English and Arabic?", "Yes. English and Arabic interfaces can be developed, including right-to-left support. Additional languages can be considered for the target market."],
    ["Which payment methods can be included?", "Depending on the provider and market, the platform may support cards, Apple Pay, Google Pay, account credit or invoice-based corporate payments. Recurring billing is subject to gateway capability and merchant eligibility."],
    ["Can existing member data be migrated?", "Potentially. Migration depends on the quality, format, ownership and export options of the existing system. Records, plans, balances and schedules must be assessed before scope is confirmed."],
    ["How long does development take?", "The timeline depends on the interfaces, design scope, feature complexity, integrations, migration, testing and approval speed. A detailed schedule is prepared after discovery."],
    ["Do you provide maintenance after launch?", "Yes. Support can include monitoring, issue resolution, compatibility updates, security and dependency updates, reporting and future development under an agreed arrangement."],
    ["Will the platform support Google Ads and Meta campaigns?", "Relevant websites and landing pages can be configured for analytics and conversion tracking using tools such as Google Analytics 4, Google Tag Manager and Meta Pixel. Mobile attribution can also be planned."],
    ["Can the app provide health or medical advice?", "A general fitness platform should not present unverified content as individual medical advice. Health, rehabilitation or nutrition features require appropriate professional input, disclaimers, consent and compliance review."],
  ],
  cta: {
    eyebrow: "Build a fitness platform designed for your members.",
    title: "Turn your fitness concept into a structured, scalable product.",
    body: "Tell us about your memberships, locations, classes, trainers and growth objectives. We will help define the member, trainer, branch and administration experiences required to move forward.",
    href: "mailto:info@webtekdigital.com?subject=Gym%20and%20fitness%20app%20development%20enquiry",
  },
};

export default function Page() {
  return <CloneAppTemplate config={config} />;
}
