import type { Metadata } from "next";
import { CloneAppTemplate } from "../../components/solutions/CloneAppTemplate";
import { createStandardSolutionConfig } from "../../components/solutions/StandardSolutionPage";

export const metadata: Metadata = {
  title: "Laundry App Development Dubai | Webtek Digital",
  description: "Build a custom laundry app in Dubai with pickup scheduling, order tracking, driver, laundry operations and admin solutions by Webtek Digital.",
};

const config = createStandardSolutionConfig({
  eyebrow: "Laundry app development Dubai",
  title: "Laundry App Development in Dubai",
  lead: "Create a seamless pickup, cleaning and delivery experience while your team manages orders, garment care, routes, payments and customer communication through one coordinated platform. We build for neighbourhood laundries, premium dry cleaners, multi-branch chains, hotel operations and on-demand marketplaces.",
  heroImage: "/services/app-development/2-slider/Home & on-demand services.png",
  heroImageAlt: "Laundry app development solution for pickup, cleaning and delivery businesses in Dubai",
  overview: [
    "A modern laundry platform brings customers, orders, pickup and delivery teams, processing facilities, payments and support together in one organised system. Customers can select services and collection times, drivers receive accurate routes and handover details, laundry teams see care instructions and production status, and administrators gain control across capacity, quality and revenue.",
    "Webtek Digital develops each component around your service catalogue, turnaround times, operating areas, processing workflow, pricing and growth plan. The platform can support scheduled collection, customer drop-off, express service, recurring subscriptions, commercial accounts, multiple branches or an approved provider marketplace.",
  ],
  metrics: [["3+", "connected customer, service and admin experiences"], ["1", "central system for orders, garments and payments"], ["24/7", "access to services, status and accounts"]],
  features: [
    ["Service catalogue", "Help customers choose the right care for clothing, household textiles and specialist items with clear pricing guidance.", ["Wash and fold, wash and iron, and dry cleaning", "Ironing, pressing and specialist care", "Duvets, curtains, shoes and bags", "Express and standard turnaround", "Per-item, per-kilogramme or package pricing"]],
    ["Easy booking", "Let customers choose an address, pickup window, service and delivery option while validating coverage and capacity.", ["On-demand and scheduled pickup", "Home, office, hotel or reception collection", "Saved addresses and map-pin validation", "Care instructions and photo attachments", "Estimates, confirmations and reminders"]],
    ["Pickup and delivery tools", "Give drivers a focused mobile workflow for routes, stops and secure handovers.", ["Daily pickup and delivery manifests", "Customer, order, parking and access details", "Navigation and arrival notifications", "Bag count, barcode scans and proof", "Failed-attempt, signature and support controls"]],
    ["Live updates", "Keep customers informed from confirmation and pickup through processing and completed delivery.", ["Driver assigned and en route", "Received at facility", "Inspection or price-adjustment request", "Cleaning, quality check and packing", "Out for delivery, receipt and support"]],
    ["Payments and offers", "Support market-appropriate pricing, payment, promotion and settlement workflows.", ["Cards and supported digital payments", "Cash or payment on delivery where permitted", "Codes, referrals and customer credit", "Prepaid bundles and subscriptions", "Corporate invoices, refunds and settlements"]],
    ["Business insights", "Use authorised dashboards to understand demand, utilisation, service quality and revenue.", ["Order volume and average value", "Service and add-on performance", "Driver and processing capacity", "Pickup, turnaround and delivery times", "Branch, zone and provider reports"]],
  ],
  modules: [
    { number: "01", label: "Customer app", title: "A convenient way to care for every garment.", text: "Give customers a simple route from service discovery to pickup scheduling, payment, tracking and aftercare across iOS, Android and responsive web experiences.", image: "/services/app-development/1-slider/Mobile App UI_UX Design.png", alt: "Customer laundry booking and order tracking app", bullets: ["Profiles, saved addresses and service discovery", "Pickup and delivery scheduling", "Care notes, bag estimates and photo uploads", "Live status, driver information and payments", "Subscriptions, order history and repeat ordering", "English, Arabic, family and corporate accounts"] },
    { number: "02", label: "Driver app", title: "Keep collections and deliveries on schedule.", text: "Convert confirmed orders into a structured workflow for employed drivers, branch vehicles, outsourced couriers or franchise partners.", image: "/services/app-development/1-slider/Android App development.png", alt: "Laundry collection and delivery driver application", bullets: ["Driver profile, documents and shift controls", "Assigned stops and optimised sequences", "Navigation, access notes and arrival controls", "Bag count, barcode scans and handover proof", "Cash status, failed attempts and rescheduling", "Signatures, incidents and performance summaries"] },
    { number: "03", label: "Laundry operations portal", title: "Move every order through processing with control.", text: "Organise facility receipt, inspection, sorting, cleaning, finishing, quality control and packing through a web or tablet portal with an auditable history.", image: "/services/app-development/1-slider/Enterprise Mobile App Development.png", alt: "Laundry operations and barcode scanning portal", bullets: ["Order intake, labels, item count and weight", "Care instructions and inspection records", "Price adjustment and customer approval", "Sorting, batches and cleaning-stage status", "Finishing, quality control and exceptions", "Packing, dispatch readiness and workload reports"] },
    { number: "04", label: "Provider or franchise portal", title: "Coordinate approved service partners.", text: "Allow providers and franchise locations to manage relevant teams, capacity, services and orders while the platform maintains central standards.", image: "/services/app-development/1-slider/React Native App Development.png", alt: "Laundry provider and franchise management portal", bullets: ["Provider onboarding and business records", "Zones, drivers, branches and facilities", "Capacity, cutoff times and order allocation", "Pricing and inspection-based quotations", "Quality, settlements, ratings and issues", "Compliance alerts and role-based access"] },
    { number: "05", label: "Admin dashboard", title: "Keep bookings and service delivery under control.", text: "Give dispatch, production, support, finance and marketing teams central visibility with permissions matched to their responsibilities.", image: "/services/app-development/1-slider/AI-Powered Mobile App Development.png", alt: "Laundry administration, dispatch and facility dashboard", bullets: ["Real-time orders, fulfilment and dispatch", "Customer, driver, team and provider management", "Services, facilities, zones and capacity", "Pricing, subscriptions, coupons and payments", "Commercial accounts, support and quality", "Analytics, audit logs and integrations"] },
  ],
  technologyLead: "A laundry platform must coordinate accounts, garment instructions, collection routes, processing stages, payments and status updates reliably. We select the architecture around expected volume, fulfilment complexity, integrations, data considerations and the long-term roadmap.",
  technologyImage: "/services/app-development/1-slider/Flutter App Development.png",
  technologyImageAlt: "Modern technology foundation for a laundry pickup and delivery platform",
  technologyTags: ["Flutter", "React Native", "Swift", "Kotlin", "React & Next.js", "Node.js", "Laravel", "Python", "REST & GraphQL", "PostgreSQL", "AWS, Google Cloud & Azure", "Maps, payments, barcode & notifications"],
  process: [
    ["Discovery and strategy", "Understand the business model, services, customers, operating areas, facilities, mobile teams, pricing, scheduling and integrations.", "A documented understanding of the proposed platform and operating requirements."],
    ["Research and planning", "Evaluate customer expectations, service workflows, market conventions, dependencies and technical constraints, then prioritise the roadmap.", "A prioritised scope, recommended architecture and delivery plan."],
    ["UX and UI design", "Map journeys for customers, drivers, laundry teams, providers, dispatchers and administrators before designing approved interfaces.", "An approved design system and interactive prototype."],
    ["Technical development", "Build the mobile apps, responsive web platform, team tools, provider portal, dashboard, APIs and databases in planned stages.", "A working platform based on the agreed scope and interfaces."],
    ["Content and integrations", "Configure approved services and pricing, then connect payments, maps, communications, analytics and business systems.", "Coordinated content and functionality across approved third-party services."],
    ["Quality assurance", "Test functional, usability, media, payment, booking, location, access-control, API and performance requirements.", "A stable release candidate prepared for client review."],
    ["Testing and launch", "Configure production environments, app listings, analytics events, support processes and release settings.", "A production-ready laundry platform with launch requirements addressed."],
    ["Ongoing support", "Provide agreed monitoring, issue resolution, security updates, compatibility work, reporting and future functionality.", "Continued technical support as the laundry platform evolves."],
  ],
  detailSections: [
    {
      eyebrow: "Advanced capabilities", title: "More than a basic booking application.", intro: "Advanced functionality can improve scheduling, repeat revenue, service quality and operating visibility in the initial release or as later phases.",
      items: [["Service zones and geofencing", "Define collection areas, exclusions, distance limits, zone fees, minimum values and driver eligibility."], ["Subscriptions and laundry plans", "Offer plans with included collections, service credits, usage limits, renewal rules and pauses."], ["Family and multi-user accounts", "Manage several users, addresses, preferences, histories and entitlements from one profile."], ["Corporate and hospitality accounts", "Support authorised users, central billing, recurring collections and account reporting."], ["Route and dispatch support", "Assign work using driver availability, location, vehicle capacity, time windows and facility cutoffs."], ["Barcode and garment tracking", "Scan order, bag or item labels through approved handover and processing stages."], ["Inspection and digital quotations", "Document condition, weight or count and request approval for price adjustments."], ["Handover and quality evidence", "Capture controlled photos, scans, checklists, notes and customer confirmation."], ["Sustainable-service information", "Present substantiated details about packaging, consolidation or approved processes."], ["Loyalty and referrals", "Encourage repeat ordering with points, credits, codes, vouchers and tiered benefits."], ["Automated service reminders", "Send relevant prompts based on time, history, entitlements and preferences."], ["Dynamic slot availability", "Adjust windows using hours, shifts, routes, facility capacity, turnaround and buffers."], ["Franchise and multi-branch management", "Separate schedules, teams, pricing and reports while retaining group controls."], ["Marketplace provider management", "Onboard providers, define commissions, manage settlements and monitor quality."], ["AI-assisted operational features", "Use reviewed support, categorisation, scheduling or reporting tools with professional oversight."]],
    },
    {
      eyebrow: "Business benefits", title: "Create a better booking and service experience.", intro: "A purpose-built platform creates a clear journey from collection to return. Sustainable value comes from technology working alongside trained teams, realistic planning, suitable products, quality control and responsive service.",
      items: [["Generate more orders", "Visible services, pickup windows, pricing and payment reduce booking friction."], ["Improve customer convenience", "Customers can book, reschedule, pay, follow progress and view service history."], ["Increase repeat revenue", "Plans, bundles, reminders, loyalty and reordering support recurring relationships."], ["Use capacity effectively", "Pickup schedules, facility workload and live status improve resource allocation."], ["Improve service quality", "Care instructions, scans, checklists, ratings and complaint workflows make quality measurable."], ["Reduce administrative work", "Automated confirmations, records, payment status and reports replace fragmented tracking."], ["Support commercial sales", "Recurring collections, approvals, billing and reporting simplify business accounts."], ["Understand performance", "Dashboards reveal demand, utilisation, revenue, retention, cancellation and quality trends."], ["Build direct relationships", "A branded platform provides control over communication, offers and first-party operational data."], ["Scale with greater control", "Add teams, vans, branches, providers and account types through structured permissions."]],
    },
    {
      eyebrow: "Industries and use cases", title: "Flexible solutions for laundry and garment-care businesses.", intro: "The platform can be configured around the way your organisation collects, processes and returns items.",
      items: [["On-demand laundry operators", "Manage areas, drivers, routes, orders, facility handovers and updates."], ["Neighbourhood laundries", "Support local discovery, pickup, counter drop-off, payments and branch reporting."], ["Premium garment-care studios", "Handle inspection, specialist cleaning, alterations, restoration and care evidence."], ["Multi-branch laundry chains", "Coordinate services, capacity, accounts and performance across locations."], ["Laundry marketplaces", "Connect customers with approved laundries through central commercial and quality controls."], ["Commercial and uniform laundry", "Manage recurring collection, item counts, approvals, billing and service reporting."], ["Hotels and serviced apartments", "Coordinate guest laundry, linen flows, property references and scheduled collections."], ["Healthcare and wellness", "Support approved workflows subject to relevant hygiene, handling and regulatory requirements."], ["Residential communities", "Offer pickup with building rules, concierge handovers and resident promotions."], ["Corporate workplaces", "Coordinate reception points, employee accounts, schedules and corporate offers."], ["Restaurants and hospitality groups", "Manage uniforms, table linen and recurring branch collections."], ["Shoe, bag and specialist cleaning", "Build journeys around inspection, photography, quotations and specialist treatments."], ["Franchise networks", "Separate operations while maintaining group standards and branding."], ["Property management and holiday homes", "Coordinate linen requests across units, housekeeping teams, owners and providers."]],
    },
    {
      eyebrow: "Why Webtek Digital", title: "Built around your service model—not a generic template.", intro: "We connect product strategy, user experience, engineering and growth planning around the practical realities of laundry operations in Dubai, the UAE and the wider GCC.",
      items: [["Custom development", "Tailored to your services, locations, teams, schedules, pricing and brand."], ["Complete user ecosystem", "Customer apps, driver tools, operations portals, admin systems, APIs and websites."], ["Marketing-first thinking", "Conversion, CRM, referrals, retention, analytics and campaign pages are planned early."], ["UAE and GCC relevance", "Support for Arabic, regional payments, hotels, towers, handovers and premium care."], ["Scalable architecture", "Structured for more customers, branches, providers, integrations and operating areas."], ["UX-focused design", "Each interface is planned around practical booking, scanning, delivery and facility tasks."], ["Transparent project management", "Requirements, responsibilities, reviews and change requests stay documented."], ["Quality assurance", "Critical booking, payment, location, fulfilment and admin journeys are tested."], ["End-to-end capability", "Strategy, branding, design, development, analytics, launch, marketing and maintenance."]],
    },
    {
      eyebrow: "Project investment", title: "How much does a laundry app cost?", intro: "Investment depends on the operating model, number of interfaces, workflow complexity and integrations. We recommend a suitable first-release scope and provide a tailored proposal after consultation rather than a restrictive public package.",
      items: [["Product scope", "Customer, driver, laundry-team, provider, administrator, iOS, Android and web requirements."], ["Operations", "Catalogue, pricing, zones, schedules, capacity, routes, scanning and processing workflows."], ["Commercial features", "Subscriptions, packages, corporate accounts, payments, refunds, commissions and settlements."], ["Platform complexity", "Inspection media, marketplace, franchise, languages, accessibility and target markets."], ["Integrations and data", "CRM, POS, barcode hardware, existing systems, migration, analytics and security."], ["Delivery and support", "Design, development, testing, launch and post-launch maintenance scope."]],
    },
    {
      eyebrow: "Free consultation", title: "Let’s discuss what you want to build.", intro: "The initial consultation helps establish which interfaces are needed, what the first release should include and how the platform can improve booking and service delivery. Your proposal will reflect the laundry platform your business actually requires.",
      items: [["Business model", "Revenue model, target customers, operating markets and fulfilment approach."], ["Services and operations", "Item categories, pricing, drivers, facilities, branches and capacity."], ["Processing and growth", "Scheduling, dispatch, scanning, quality, subscriptions, packages and promotions."], ["Applications and systems", "Required apps, portals, payments, commercial accounts, migration and integrations."], ["Delivery planning", "Initial priorities, target launch period, delivery approach and next steps."], ["Send your requirements", "Share an existing project brief or discuss your requirements during a free consultation."]],
    },
  ],
  faqTitle: "Laundry App Development FAQs",
  faqs: [
    ["What is a laundry app?", "A laundry app lets customers choose garment-care services, arrange pickup and delivery, provide care instructions, pay and follow order progress. A complete solution can also include driver, operations, provider and administration tools."],
    ["Can Webtek Digital build a custom laundry app in Dubai?", "Yes. Services, bookings, locations, mobile teams, payments and integrations can be tailored for laundry businesses in Dubai and across the UAE."],
    ["Can the app support pickup, delivery and customer drop-off?", "Yes. It can combine home or office collection with branch drop-off and counter collection, using different availability, pricing and workflows."],
    ["Which applications and portals are included?", "A solution may include a customer app, responsive ordering website, driver app, laundry operations portal, provider or franchise portal, admin dashboard and marketing website. The final combination follows discovery."],
    ["Can customers add special garment-care instructions?", "Yes. Customers can add notes, preferred methods, appropriate allergy-related requests and photographs. Laundry teams can review instructions and request clarification."],
    ["Can the app manage subscriptions and prepaid packages?", "Yes. It can support recurring plans, prepaid bundles, service credits, limits, renewal, expiry and package balances according to approved rules."],
    ["Can drivers receive and update pickup or delivery tasks?", "Yes. Driver apps can provide assignments, navigation, customer details, status controls, scanning, proof, confirmation and payment status."],
    ["Can the platform support multiple branches or franchises?", "Yes. Services, pricing, schedules, capacity, teams and reports can be managed by location while central administrators retain oversight."],
    ["Can hotels and corporate accounts schedule recurring collections?", "Yes. Business accounts can include authorised users, locations, recurring schedules, approvals, billing and service-level reporting."],
    ["Can customers track the driver?", "Potentially. Location and estimated-arrival updates can be included where appropriate; accuracy depends on permissions, connectivity, mapping services and workflow."],
    ["Which payment methods can be included?", "Depending on provider and market, options may include cards, Apple Pay, Google Pay, cash, credit or corporate invoicing. Recurring billing depends on gateway capability and merchant eligibility."],
    ["Can the application support English and Arabic?", "Yes. English and Arabic interfaces can be developed, including right-to-left layouts, with other languages considered for the target market."],
    ["Can existing customer and order data be migrated?", "Potentially. Feasibility depends on the quality, format, ownership and export options of the existing system and must be assessed before scope is confirmed."],
    ["How long does development take?", "Timing depends on interface count, design scope, feature complexity, integrations, migration, testing and approval speed. A detailed schedule follows discovery."],
    ["Do you provide maintenance after launch?", "Yes. Support can cover monitoring, issue resolution, compatibility, security and dependency updates, reporting and future development under a separate agreement."],
    ["Will the platform support Google Ads and Meta campaigns?", "Relevant websites can be configured for GA4, Google Tag Manager and Meta Pixel conversion tracking, with mobile attribution planned as required."],
    ["Can the platform support barcode or QR-code tracking?", "Yes. Orders, bags or items can receive barcodes or QR codes scanned at approved handover and processing stages. Hardware, labels and tracking depth are confirmed during discovery."],
    ["Can customers approve price changes after inspection?", "Yes. If count, weight, fabric or condition changes the estimate, the platform can request approval before processing under clearly defined response rules."],
  ],
  cta: { eyebrow: "Planning a laundry platform?", title: "Build a better booking and service experience.", body: "Tell us about your services, operating areas, facilities, teams, branches and growth objectives. We’ll help define the customer, driver, operations, provider and administration experiences you need.", href: "mailto:info@webtekdigital.com?subject=Laundry app development enquiry" },
});

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: config.faqs?.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })),
};

export default function Page() {
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema).replace(/</g, "\\u003c") }} /><CloneAppTemplate config={config} /></>;
}
