import type { Metadata } from "next";
import { CloneAppTemplate } from "../../components/solutions/CloneAppTemplate";
import { createStandardSolutionConfig } from "../../components/solutions/StandardSolutionPage";

export const metadata: Metadata = { title: "Laundry App Development Dubai | Webtek Digital", description: "Custom laundry and dry-cleaning app development for businesses in Dubai and the UAE." };
const config = createStandardSolutionConfig({
  eyebrow: "Laundry and dry-cleaning platform", title: "Laundry app development in Dubai", lead: "Create a seamless pickup, cleaning and delivery experience with a branded app built around your laundry operation.",
  overview: ["A laundry platform coordinates customers, pickup and delivery teams, garment care, payments and support through one connected workflow.", "We shape the product around your services, turnaround times, coverage zones and preferred way of working."], metrics: [["3", "connected user products"], ["1", "central operations hub"], ["24/7", "customer access"]],
  features: [["Service catalogue", "Show cleaning, pressing, alterations and specialist-care services clearly."], ["Pickup scheduling", "Let customers choose convenient collection and delivery slots."], ["Order tracking", "Share timely updates from collection through cleaning and return."], ["Driver coordination", "Give field teams route, order and collection-status tools."], ["Flexible pricing", "Manage item pricing, subscriptions, offers and secure payments."], ["Operations reporting", "Track orders, turnaround times, customers and revenue in one place."]],
  modules: [{ number: "01", label: "Customer app", title: "Laundry care that fits into everyday life.", text: "Customers can schedule pickups, add care notes, track an order and pay with confidence.", image: "/solutions/talabat/An intuitive experience that drives repeat orders..png", alt: "Laundry customer app" }, { number: "02", label: "Driver app", title: "Keep collections and deliveries on schedule.", text: "Drivers receive collection details, route guidance and clear delivery-status controls.", image: "/solutions/talabat/Keep delivery partners moving efficiently..png", alt: "Laundry driver app" }, { number: "03", label: "Operations dashboard", title: "A clear view across every garment order.", text: "Manage services, orders, drivers, customers, payments and support from one dashboard.", image: "/solutions/talabat/Manage the entire marketplace in one place..png", alt: "Laundry operations dashboard" }],
  technologyLead: "A scalable foundation supports reliable scheduling, status updates and customer service as your laundry business expands.", technologyTags: ["iOS and Android", "Operations dashboard", "Secure APIs", "Cloud deployment", "Payment integration", "Notifications"], process: [["Discovery & strategy", "Map your services, pickup model and operating areas."], ["UX/UI design", "Create effortless customer and delivery journeys."], ["Development", "Build the customer, driver and operations experiences."], ["Testing & launch", "Test key collection, payment and delivery workflows."]], cta: { eyebrow: "Planning a laundry platform?", title: "Let’s make laundry simpler for your customers.", body: "We can help you define and build a platform that fits your service model.", href: "mailto:info@webtekdigital.com?subject=Laundry app development enquiry" },
});
export default function Page() { return <CloneAppTemplate config={config} />; }
