import type { Metadata } from "next";
import { CloneAppTemplate, type CloneAppTemplateConfig } from "../../components/solutions/CloneAppTemplate";

export const metadata: Metadata = {
  title: "Talabat Clone App Development Dubai | Food Delivery App Development | Webtek Digital",
  description: "Launch your own food delivery platform with a custom Talabat Clone App developed by Webtek Digital. Complete customer, restaurant, driver and admin applications with secure payments, live tracking and scalable technology.",
};

const config: CloneAppTemplateConfig = {
  eyebrow: "Food delivery platform development",
  title: "Talabat Clone App Development in Dubai",
  lead: "Launch a powerful food ordering and delivery app inspired by Talabat. Webtek Digital develops fully customised, fast and scalable platforms for startups, restaurant businesses and regional marketplaces.",
  primaryCta: "Book a Free Consultation",
  secondaryCta: "Request a Live Demo",
  heroImage: "/talabat/banner-wel.png.webp",
  heroImageAlt: "Talabat-style food delivery application shown on mobile devices",
  overview: ["Running a successful food delivery platform requires much more than a mobile application. You need a complete ecosystem that connects customers, restaurants, delivery partners and administrators through one intelligent platform.", "Our Talabat Clone solution simplifies operations, automates workflows and creates a seamless ordering experience from order placement to delivery. Built for scalability, it can grow from a single city to multiple regions."],
  metrics: [["4", "dedicated user applications"], ["1", "central admin dashboard"], ["1,000s", "daily orders supported"]],
  features: [["Multi-vendor marketplace", "Onboard and manage unlimited restaurants, branches, menus and availability from one platform."], ["Seamless customer ordering", "Fast browsing, secure checkout, live tracking, wallet payments and repeat-order tools."], ["Restaurant management", "Give partners independent control of menus, pricing, incoming orders, promotions and inventory."], ["Smart delivery operations", "Use live GPS tracking, automated driver assignment and real-time order management."], ["Flexible business controls", "Set delivery fees, commissions, service zones, payment methods and operating rules."], ["Marketing and promotions", "Run coupons, referrals, loyalty programmes, offers and customer engagement campaigns."]],
  modules: [{ number: "01", label: "Customer app", title: "An intuitive experience that drives repeat orders.", text: "Customers can use smart search, cuisine filters, favourite restaurants, menu variants, secure checkout, Apple Pay or Google Pay, wallet payments, promo codes, loyalty rewards, live driver tracking, push notifications, reviews, order history and support.", image: "/talabat/customer-panel.png.webp", alt: "Customer food delivery application screen" }, { number: "02", label: "Restaurant partner panel", title: "Independent controls for every restaurant.", text: "Restaurant teams can manage menus, real-time orders, offers and discounts, business analytics, sales reports, branches, inventory status and customer reviews without depending on your internal team.", image: "/talabat/app-screen3.png.webp", alt: "Restaurant partner delivery application screens" }, { number: "03", label: "Driver app", title: "Keep delivery partners moving efficiently.", text: "Driver features include smart order allocation, live GPS navigation, an earnings dashboard, route optimisation, delivery history, online and offline mode, contactless delivery and in-app support.", image: "/talabat/banner-wel.png.webp", alt: "Food delivery driver application shown in phone mockups" }, { number: "04", label: "Admin dashboard", title: "Manage the entire marketplace in one place.", text: "Control customers, restaurant approvals, drivers, live orders, commissions, refunds, coupons, notifications, finance reports and business intelligence from one connected dashboard.", image: "/talabat/all-language.webp", alt: "Food delivery platform administration technology stack" }],
  technologyLead: "Our platform can be built around the mobile, frontend, backend, cloud, payment, maps, notification and security technologies that best match your business requirements.",
  technologyImage: "/talabat/all-language.webp",
  technologyImageAlt: "Application development technology stack",
  technologyTags: ["Flutter / Native iOS & Android", "React / Next.js", "Node.js / Laravel / .NET", "PostgreSQL / MySQL / MongoDB", "AWS / Azure / Google Cloud", "Stripe / Checkout.com / Telr / PayTabs", "Google Maps / Mapbox", "Firebase / Email / SMS / WhatsApp API", "SSL / RBAC / Encrypted APIs"],
  process: [["Discovery & strategy", "We define the market, business model, users, delivery workflow and launch priorities."], ["UX/UI design", "We plan customer, restaurant, driver and administrator journeys around your brand."], ["Agile development", "We build the connected applications and marketplace capabilities in focused delivery phases."], ["Testing & QA", "Critical ordering, payment, tracking and operational flows are tested before release."], ["Deployment", "The platform is prepared for a reliable production launch on the right cloud infrastructure."], ["Ongoing support & scaling", "We remain a long-term technology partner as your platform, users and regions grow."]],
  cta: { eyebrow: "Ready to build your delivery platform?", title: "Book a free consultation or request a live demo.", body: "Pricing and timelines are customised around your business requirements. Work with a technology partner that delivers scalable architecture, enterprise-grade security, exceptional UX and complete source-code ownership.", href: "mailto:info@webtekdigital.com?subject=Talabat clone app development consultation" },
};

export default function Page() { return <CloneAppTemplate config={config} />; }
