import type { Metadata } from "next";
import { CloneAppTemplate } from "../../components/solutions/CloneAppTemplate";
import { createStandardSolutionConfig } from "../../components/solutions/StandardSolutionPage";

export const metadata: Metadata = { title: "Car Wash App Development Dubai | Webtek Digital", description: "Custom car wash booking app development for businesses in Dubai and the UAE." };

const config = createStandardSolutionConfig({
  eyebrow: "Car wash booking platform", title: "Car wash app development in Dubai", lead: "Make it easy for drivers to book a wash, choose a location and keep their vehicles looking their best with a branded digital platform.",
  overview: ["A modern car wash platform brings customer bookings, mobile teams, fixed locations, payments and support together in one organised system.", "We tailor every experience around your services, operating areas, appointment capacity and customer-care standards."],
  metrics: [["3", "connected user products"], ["1", "central operations hub"], ["24/7", "booking availability"]],
  features: [["Service discovery", "Present wash packages, add-ons, prices and availability clearly."], ["Easy booking", "Let customers choose a service, time and preferred location in a few taps."], ["Mobile team tools", "Give wash professionals job details, route information and status controls."], ["Live updates", "Keep customers informed from booking confirmation to job completion."], ["Payments and offers", "Support secure payments, packages, subscriptions and promotional codes."], ["Business insights", "Monitor bookings, team performance, revenue and repeat customers."]],
  modules: [{ number: "01", label: "Customer app", title: "A convenient way to care for every vehicle.", text: "Customers can select services, book a slot, manage addresses, pay securely and follow their appointment.", image: "/solutions/talabat/An intuitive experience that drives repeat orders..png", alt: "Car wash customer app" }, { number: "02", label: "Service team app", title: "Give teams the details they need on the road.", text: "Manage assigned jobs, arrival status, service notes and completed work from one focused interface.", image: "/solutions/talabat/Keep delivery partners moving efficiently..png", alt: "Car wash team app" }, { number: "03", label: "Operations dashboard", title: "Keep bookings and service delivery under control.", text: "Oversee teams, services, locations, payments, customer support and performance reporting.", image: "/solutions/talabat/Manage the entire marketplace in one place..png", alt: "Car wash operations dashboard" }],
  technologyLead: "The platform can be built for dependable scheduling, location-aware service and a smooth customer experience as your operation grows.", technologyTags: ["iOS and Android", "Operations dashboard", "Secure APIs", "Cloud deployment", "Payment integration", "Push notifications"],
  process: [["Discovery & strategy", "Define your services, teams, locations and commercial model."], ["UX/UI design", "Design simple booking and service-delivery journeys around your brand."], ["Development", "Build the customer, team and operations products in focused phases."], ["Testing & launch", "Validate the essential booking, payment and service flows before release."]],
  cta: { eyebrow: "Ready to digitise your car wash business?", title: "Let’s build a better booking experience.", body: "Talk to our team about a car wash platform tailored to your operations and growth plans.", href: "mailto:info@webtekdigital.com?subject=Car wash app development enquiry" },
});
export default function Page() { return <CloneAppTemplate config={config} />; }
