import type { Metadata } from "next";
import { CloneAppTemplate } from "../../components/solutions/CloneAppTemplate";
import { createStandardSolutionConfig } from "../../components/solutions/StandardSolutionPage";

export const metadata: Metadata = {
  title: "Car Wash App Development Dubai | Webtek Digital",
  description: "Build a custom car wash app in Dubai with customer booking, mobile team, subscription and admin solutions developed by Webtek Digital.",
};

const config = createStandardSolutionConfig({
  eyebrow: "Car wash app development Dubai",
  title: "Car Wash App Development in Dubai",
  lead: "Make it easier for drivers to book a wash, choose a location or request mobile service while your team manages schedules, payments and service delivery through one coordinated platform. We build for fixed-location wash centres, mobile car wash teams, detailing studios, fleet services and multi-vendor marketplaces.",
  heroImage: "/services/web-development/1-slider/Automotive.png",
  heroImageAlt: "Car wash app development solution for mobile and fixed-location vehicle cleaning businesses in Dubai",
  overview: [
    "A modern car wash platform brings customer bookings, vehicle details, mobile teams, wash bays, locations, payments and support together in one organised system. Customers can select a suitable service and time, field teams receive accurate job information, and administrators gain visibility across schedules, capacity, quality and revenue.",
    "Webtek Digital develops every component around your service menu, fulfilment model, operating areas, team structure, pricing and growth plan. The platform can support home or office service, fixed-location appointments, drive-in queues, detailing packages, recurring subscriptions, corporate fleets or an approved provider marketplace.",
  ],
  metrics: [["3+", "connected customer, team and admin experiences"], ["1", "central system for bookings, vehicles and payments"], ["24/7", "access to services, status and accounts"]],
  features: [
    ["Service discovery", "Help customers choose the right wash or detailing service for their vehicle, with clear information before booking.", ["Exterior, interior and complete wash categories", "Express, standard and premium packages", "Vehicle type, duration and price", "Mobile or fixed-location availability", "Add-ons, ratings and seasonal offers"]],
    ["Easy booking", "Let customers add a vehicle, choose where the service takes place and select a convenient date or time.", ["Immediate and scheduled bookings", "Home, office or wash-centre selection", "Time-slot and capacity validation", "Multiple vehicles and special instructions", "Confirmations and reminders"]],
    ["Mobile team tools", "Give technicians and wash teams a focused workflow for assignments, travel, service records and completion.", ["Daily and weekly schedules", "Customer, vehicle and access details", "Arrival, start and completion status", "Digital checklists and photographs", "Customer confirmation and payment status"]],
    ["Live updates", "Keep customers informed from booking confirmation through completion and make delays easier to manage.", ["Team assignment and en-route status", "Estimated arrival information", "Work-in-progress updates", "Add-on approval requests", "Completion, receipt and support notifications"]],
    ["Payments and offers", "Support payment, promotion and pricing workflows according to the selected provider and market.", ["Cards and supported digital payments", "Promotional codes and referrals", "Prepaid bundles and subscriptions", "Corporate invoicing", "Refund, tax and settlement records"]],
    ["Business insights", "Use authorised dashboards to understand demand, utilisation, quality, revenue and retention.", ["Booking and completion volume", "Revenue and average order value", "Team and bay utilisation", "Repeat booking and subscription activity", "Branch, zone and provider reports"]],
  ],
  modules: [
    { number: "01", label: "Customer app", title: "A convenient way to care for every vehicle.", text: "Give drivers a simple route from service discovery to booking, payment and aftercare across iOS, Android and responsive web experiences.", image: "/services/app-development/1-slider/Mobile App UI_UX Design.png", alt: "Customer car wash booking app interface", bullets: ["Profiles, saved addresses and multiple vehicles", "Services, packages, add-ons and available slots", "Map pin, location validation and photo uploads", "Live updates, payments, receipts and rebooking", "English and Arabic interfaces", "Subscriptions, family and corporate accounts"] },
    { number: "02", label: "Mobile team app", title: "Give teams the details they need on the road.", text: "Convert bookings into a structured daily workflow for mobile teams, technicians, vans and approved providers.", image: "/services/app-development/1-slider/Android App development.png", alt: "Mobile wash technician application", bullets: ["Shift, availability and assignment controls", "Navigation, parking and access instructions", "Service checklists and before-and-after photos", "Materials, incidents and additional-work requests", "Completion signature and payment status", "Daily performance and compliance alerts"] },
    { number: "03", label: "Provider or franchise portal", title: "Coordinate approved service partners.", text: "Allow providers or franchise locations to manage relevant capacity, services and bookings while maintaining central standards and commercial control.", image: "/services/app-development/1-slider/Enterprise Mobile App Development.png", alt: "Car wash provider and franchise management portal", bullets: ["Provider onboarding and approval", "Branches, bays, zones, teams and mobile units", "Booking acceptance and allocation", "Pricing, quality and settlement summaries", "Ratings, compliance and document alerts", "Role-based provider access"] },
    { number: "04", label: "Admin dashboard", title: "Keep bookings and service delivery under control.", text: "Give operations, dispatch, support, finance and marketing teams central visibility with role-based access.", image: "/services/app-development/1-slider/AI-Powered Mobile App Development.png", alt: "Car wash administration and dispatch dashboard", bullets: ["Real-time bookings, schedules and dispatch", "Customer, vehicle, team and provider management", "Services, pricing, zones, branches and capacity", "Subscriptions, coupons, payments and settlements", "Fleet accounts, support and quality review", "Reports, permissions, audit logs and integrations"] },
  ],
  technologyLead: "We select the architecture according to expected activity, fulfilment complexity, integration requirements, data considerations and the long-term roadmap—not popularity alone.",
  technologyImage: "/services/app-development/1-slider/React Native App Development.png",
  technologyImageAlt: "Modern technology foundation for a car wash booking platform",
  technologyTags: ["Flutter", "React Native", "Swift", "Kotlin", "React & Next.js", "Node.js", "Laravel", "Python", "REST & GraphQL", "PostgreSQL", "AWS, Google Cloud & Azure", "Maps, payments & notifications"],
  process: [
    ["Discovery and strategy", "Understand the business model, services, customers, operating areas, teams, pricing, scheduling, payments and growth objectives.", "A documented understanding of the proposed platform and operating requirements."],
    ["Research and planning", "Evaluate customer expectations, team workflows, market conventions, dependencies and technical constraints, then prioritise the roadmap.", "A prioritised scope, recommended architecture and delivery plan."],
    ["UX and UI design", "Map journeys for customers, technicians, providers, dispatchers and administrators before designing approved interfaces.", "An approved design system and interactive prototype."],
    ["Technical development", "Build the mobile apps, responsive web platform, team tools, provider portal, dashboard, APIs and databases in planned stages.", "A working platform based on the agreed scope and interfaces."],
    ["Content and integrations", "Configure approved services and pricing, then connect payments, maps, communications, analytics and business systems.", "Coordinated content and functionality across approved third-party services."],
    ["Quality assurance", "Test functional, usability, media, payment, booking, location, access-control, API and performance requirements.", "A stable release candidate prepared for client review."],
    ["Testing and launch", "Configure production environments, app listings, analytics events, support processes and release settings.", "A production-ready platform with launch requirements addressed."],
    ["Ongoing support", "Provide agreed monitoring, issue resolution, security updates, compatibility work, reporting and future functionality.", "Continued technical support as the platform evolves."],
  ],
  detailSections: [
    {
      eyebrow: "Advanced capabilities", title: "More than a basic booking application.", intro: "Advanced functionality can improve scheduling, repeat revenue, service quality and operating visibility. Features can be included in the first release or phased according to business priorities.",
      items: [
        ["Service zones and geofencing", "Define mobile areas, exclusions, distance limits, zone pricing and team eligibility."], ["Subscriptions and wash plans", "Offer plans with included services, usage limits, eligible vehicles, renewal rules and pause options."], ["Multi-vehicle accounts", "Manage several vehicles, preferences, histories and package entitlements from one profile."], ["Corporate and fleet accounts", "Support authorised users, central billing, vehicle lists, scheduled service and reporting."], ["Route and dispatch support", "Assign mobile jobs according to availability, location, capacity and appointment windows."], ["Bay and queue management", "Coordinate bays, appointment capacity, service time, walk-ins and branch workload."], ["Inspection and digital quotations", "Document condition and request approval for additional work before it begins."], ["Before-and-after evidence", "Capture photographs, checklists, notes and confirmation in a traceable service record."], ["Waterless and eco-service tracking", "Label approved methods and record service or product use without unverified claims."], ["Loyalty and referrals", "Encourage repeat booking through points, credits, referrals, vouchers and tiered benefits."], ["Automated service reminders", "Send relevant prompts based on time, previous bookings, entitlements and preferences."], ["Dynamic slot availability", "Adjust appointments using hours, shifts, duration, travel, bay capacity and buffers."], ["Franchise and multi-branch management", "Separate teams, pricing and reporting while retaining group-level control."], ["Marketplace provider management", "Onboard providers, define commissions, manage settlements and monitor eligibility and quality."], ["AI-assisted operational features", "Use reviewed tools for support, categorisation, scheduling assistance or reporting with professional oversight."],
      ],
    },
    {
      eyebrow: "Business benefits", title: "Create a better booking and service experience.", intro: "A purpose-built platform creates a clear journey from service selection to completion. Sustainable value comes from technology working alongside trained teams, realistic planning, quality control and responsive service.",
      items: [["Generate more bookings", "Visible services, availability, vehicle pricing and payment reduce booking friction."], ["Improve customer convenience", "Customers can book, reschedule, pay, follow progress and view service history."], ["Increase repeat revenue", "Plans, prepaid packages, reminders, loyalty and rebooking support recurring relationships."], ["Use capacity effectively", "Schedules, service duration, travel data and status improve team allocation."], ["Improve service quality", "Checklists, photographs, ratings and complaint workflows make quality measurable."], ["Reduce administrative work", "Automated confirmations, records, payment status and reports replace fragmented tracking."], ["Support fleet and corporate sales", "Vehicle lists, approvals, billing and reports make business accounts manageable."], ["Understand performance", "Dashboards reveal demand, utilisation, revenue, retention, cancellation and quality trends."], ["Build direct relationships", "A branded platform provides control over communication, offers and first-party operational data."], ["Scale with greater control", "Add teams, vans, branches, providers and service areas through structured permissions."]],
    },
    {
      eyebrow: "Industries and use cases", title: "Flexible solutions for vehicle care businesses.", intro: "The platform can be configured around the way your organisation sells, schedules and fulfils vehicle-care services.",
      items: [["Mobile car wash operators", "Manage areas, vans, teams, routes, payments and updates."], ["Fixed-location wash centres", "Support branches, slots, bays, queues, packages and reporting."], ["Premium detailing studios", "Handle inspection, quotations, specialist work and service evidence."], ["Multi-branch wash chains", "Coordinate services, capacity, accounts and performance across locations."], ["Car wash marketplaces", "Connect customers with approved providers through central commercial and quality controls."], ["Corporate fleets", "Schedule recurring or on-demand cleaning with authorised users and central billing."], ["Rental and leasing companies", "Coordinate cleaning between hires and across branches."], ["Dealerships and automotive groups", "Manage display, demo, customer and pre-delivery vehicle cleaning."], ["Residential communities", "Offer on-site services with property rules, time windows and resident booking."], ["Office parks", "Coordinate workplace services with defined parking areas and appointment windows."], ["Hotels and hospitality", "Support guest, valet-related and fleet cleaning requests."], ["Waterless and steam-cleaning services", "Build journeys around suitable methods, equipment and supported claims."], ["Franchise networks", "Separate operations while maintaining group standards and branding."], ["Automotive service platforms", "Combine washing with approved maintenance, tyre, fuel, parking or care services."]],
    },
    {
      eyebrow: "Why Webtek Digital", title: "Built around your service model—not a generic template.", intro: "We connect product strategy, user experience, engineering and growth planning around the practical realities of vehicle-care operations in Dubai, the UAE and the wider GCC.",
      items: [["Custom development", "Tailored to your services, locations, teams, schedules, pricing and brand."], ["Complete user ecosystem", "Customer apps, team tools, provider portals, admin systems, APIs and websites."], ["Marketing-first thinking", "Conversion, CRM, referrals, retention, analytics and campaign pages are planned early."], ["UAE and GCC relevance", "Support for Arabic, regional payments, towers, villas, service zones and premium care."], ["Scalable architecture", "Structured for more customers, branches, providers, integrations and operating areas."], ["UX-focused design", "Each interface is planned around the real tasks of its user."], ["Transparent project management", "Requirements, responsibilities, reviews and change requests stay documented."], ["Quality assurance", "Critical booking, scheduling, payment, job and admin journeys are tested."], ["End-to-end capability", "Strategy, branding, design, development, analytics, launch, marketing and maintenance."]],
    },
    {
      eyebrow: "Project investment", title: "How much does a car wash app cost?", intro: "Investment depends on the operating model, interfaces, feature complexity and integrations. After an initial consultation, we recommend a suitable first-release scope and provide a tailored proposal rather than a restrictive public package.",
      items: [["Product scope", "Customer, team, provider, administrator, iOS, Android and responsive web requirements."], ["Operations", "Service pricing, zones, scheduling, dispatch, bays, queues, branches and fleets."], ["Commercial features", "Subscriptions, packages, recurring billing, payments, refunds, commissions and settlements."], ["Platform complexity", "Media, inspection, marketplace, franchise, languages, accessibility and target markets."], ["Integrations and data", "CRM, POS, existing systems, migration, analytics and security requirements."], ["Delivery and support", "Design, development, testing, launch and post-launch maintenance scope."]],
    },
    {
      eyebrow: "Free consultation", title: "Let’s discuss what you want to build.", intro: "The initial consultation helps establish which interfaces are required, what the first release should include and how the platform can improve booking and service delivery. Your proposal will reflect the platform your business actually needs.",
      items: [["Business model", "Revenue model, target customers, operating markets and fulfilment approach."], ["Services and operations", "Vehicle categories, pricing, teams, vans, branches and capacity."], ["Scheduling and growth", "Dispatch, service zones, subscriptions, packages and promotions."], ["Applications and systems", "Required apps, portals, payments, fleets, migration and integrations."], ["Delivery planning", "Initial priorities, target launch period, delivery approach and next steps."], ["Send your requirements", "Share an existing brief or discuss the requirements with our team during a free consultation."]],
    },
  ],
  faqTitle: "Car Wash App Development FAQs",
  faqs: [
    ["What is a car wash app?", "A car wash app lets customers choose a vehicle-cleaning service, add vehicle details, book a location or mobile visit, pay and follow progress. A complete solution can also include team, provider and administration tools."],
    ["Can Webtek Digital build a custom car wash app in Dubai?", "Yes. Services, bookings, locations, mobile teams, payments and integrations can be tailored for businesses in Dubai and across the UAE."],
    ["Can the app support mobile and fixed-location car washing?", "Yes. It can combine home or office service with wash-centre appointments, with different pricing, capacity and workflows for each fulfilment type."],
    ["Which applications and portals are included?", "A solution may include a customer app, responsive booking website, mobile team app, provider or franchise portal, administration dashboard and marketing website. The final combination is confirmed after discovery."],
    ["Can customers save more than one vehicle?", "Yes. Customers can maintain multiple profiles with vehicle category, model, registration, preferences and service history."],
    ["Can the app manage subscriptions and prepaid packages?", "Yes. It can support recurring plans, prepaid bundles, entitlements, limits, renewal, expiry and balances according to approved commercial rules."],
    ["Can mobile teams receive and update jobs?", "Yes. Team apps can provide assignments, navigation, requirements, statuses, checklists, photos, customer confirmation and payment status."],
    ["Can the platform support multiple branches or franchises?", "Yes. Services, pricing, schedules, capacity, teams and reports can be managed by location while central administrators retain oversight."],
    ["Can corporate fleets book recurring washes?", "Yes. Fleet accounts can include authorised users, vehicle lists, recurring schedules, approvals, account billing and service reporting."],
    ["Can customers track the mobile team?", "Potentially. Location and estimated-arrival updates can be included where appropriate; accuracy depends on permissions, connectivity, mapping services and workflow."],
    ["Which payment methods can be included?", "Depending on the provider and market, options may include cards, Apple Pay, Google Pay, cash, credit or corporate invoicing. Recurring billing depends on gateway capability and merchant eligibility."],
    ["Can the application support English and Arabic?", "Yes. English and Arabic interfaces can be developed, including right-to-left layouts, with other languages considered for the target market."],
    ["Can existing customer and booking data be migrated?", "Potentially. Feasibility depends on the quality, format, ownership and export options of the existing system and must be assessed before scope is confirmed."],
    ["How long does development take?", "Timing depends on interface count, design scope, feature complexity, integrations, migration, testing and approval speed. A detailed schedule follows discovery and scope confirmation."],
    ["Do you provide maintenance after launch?", "Yes. Support can cover monitoring, issue resolution, compatibility, security and dependency updates, reporting and future development under a separate agreement."],
    ["Will the platform support Google Ads and Meta campaigns?", "Relevant websites and landing pages can be configured for GA4, Google Tag Manager and Meta Pixel conversion tracking, with mobile attribution planned as required."],
    ["Can the app make environmental claims about water savings?", "Only substantiated claims should be published. Statements about water, products, emissions or environmental impact should be supported by credible evidence and reviewed for applicable requirements."],
  ],
  cta: { eyebrow: "Ready to digitise your car wash business?", title: "Build a better booking and service experience.", body: "Tell us about your services, operating areas, teams, branches and growth objectives. We’ll help define the customer, service-team, provider and administration experiences you need.", href: "mailto:info@webtekdigital.com?subject=Car wash app development enquiry" },
});

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: config.faqs?.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })),
};

export default function Page() {
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema).replace(/</g, "\\u003c") }} /><CloneAppTemplate config={config} /></>;
}
