import type { Metadata } from "next";
import { CloneAppTemplate } from "../../components/solutions/CloneAppTemplate";
import { createStandardSolutionConfig } from "../../components/solutions/StandardSolutionPage";

export const metadata: Metadata = {
  title: "Grocery App Development Dubai | Webtek Digital",
  description: "Build a custom grocery delivery app in Dubai with customer, store, fulfilment, driver and admin solutions developed by Webtek Digital.",
};

const config = createStandardSolutionConfig({
  eyebrow: "Grocery app development Dubai",
  title: "Grocery App Development in Dubai",
  lead: "Build a convenient grocery-ordering experience with fast product discovery, secure checkout and coordinated fulfilment while your teams manage catalogues, inventory, orders and delivery from one connected platform. We develop scalable grocery applications around your commercial model and customer journey for supermarkets, dark stores, local retailers and multi-vendor marketplaces.",
  heroImage: "/solutions/grocery/grocery-delivery-app-hero.png",
  heroImageAlt: "Grocery app development solution for online ordering and delivery businesses in Dubai",
  overview: [
    "A modern grocery platform connects shoppers, product catalogues, stores, inventory, fulfilment teams, delivery partners, payments and support through one organised system. Customers receive reliable availability and simple ordering, while teams gain practical picking, substitution and delivery workflows.",
    "Webtek Digital develops every component around your assortment, store network, fulfilment model, service areas, delivery structure, pricing and growth plan. The platform can support one supermarket, several branches, dark stores, scheduled delivery, click and collect, business accounts or an approved multi-vendor marketplace.",
  ],
  metrics: [["4+", "connected shopper, store, driver and admin experiences"], ["1", "central system for catalogues, inventory and orders"], ["24/7", "access to products, order status and accounts"]],
  features: [
    ["Product discovery", "Help shoppers find everyday essentials quickly through clear categories, relevant search, filters and merchandising.", ["Departments, categories and subcategories", "Keyword search and suggestions", "Brand, price and attribute filters", "Variants, pack sizes and units", "Availability by store or fulfilment location", "Favourites and saved shopping lists"]],
    ["Smart checkout", "Create a clear basket and checkout journey for quantities, delivery details, substitutions, promotions and payment.", ["Persistent basket and saved addresses", "Immediate or scheduled delivery", "Click-and-collect where required", "Delivery-slot availability", "Substitution preferences", "Fees, tax and order summary"]],
    ["Inventory controls", "Give store and catalogue teams practical controls for stock availability, pricing and product status.", ["Stock availability by store", "Low-stock and out-of-stock controls", "Price and promotion updates", "Variant and unit management", "Inventory import and export", "Integration logs and exceptions"]],
    ["Live updates", "Keep customers informed from confirmation through fulfilment and delivery while helping support teams respond to issues.", ["Store acceptance and picking status", "Substitution requests", "Packed and driver-assigned updates", "Estimated arrival", "Delivery completion", "Digital receipt and support access"]],
    ["Payments and offers", "Support convenient payment, pricing and promotional workflows according to the selected provider and market.", ["Cards and supported digital payments", "Cash on delivery where permitted", "Coupons, vouchers and referrals", "Loyalty and membership benefits", "Business account invoicing", "Refund and settlement records"]],
    ["Business insights", "Provide authorised teams with dashboards and reports for demand, availability, fulfilment quality and revenue.", ["Orders, sales and average order value", "Category and product performance", "Availability and substitutions", "Picking and delivery times", "Repeat purchase and loyalty activity", "Store, zone and merchant comparisons"]],
  ],
  modules: [
    { number: "01", label: "Customer app", title: "Everyday groceries, effortlessly ordered.", text: "Give shoppers a simple route from store or product discovery to basket, payment and delivery tracking across iOS, Android and responsive web experiences.", image: "/solutions/grocery/grocery-customer-ordering-app.png", alt: "Customer grocery ordering and checkout application", bullets: ["Profiles, saved addresses and store availability", "Product search, filters, variants and favourites", "Persistent baskets and substitution preferences", "Delivery or collection scheduling", "Payments, loyalty, tracking and repeat ordering", "English, Arabic, family and business accounts"] },
    { number: "02", label: "Store and fulfilment portal", title: "Practical tools for store and fulfilment teams.", text: "Convert confirmed orders into a structured picking, substitution, packing and handover workflow adapted to each fulfilment location.", image: "/solutions/grocery/grocery-fulfilment-admin-platform.png", alt: "Grocery store picking and substitution portal", bullets: ["Incoming order queue and acceptance", "Category-based picking lists", "Item scans and weighted-price adjustments", "Out-of-stock and substitution workflows", "Packing and readiness controls", "Driver handover and fulfilment history"] },
    { number: "03", label: "Delivery partner app", title: "Clear delivery tasks from collection to handover.", text: "Give drivers the collection, navigation, customer and status information needed to complete secure deliveries.", image: "/services/app-development/2-slider/Logistics and delivery solutions.png", alt: "Grocery delivery partner application", bullets: ["Availability and delivery requests", "Store collection information", "Routes and navigation", "Live status and customer communication", "Proof of delivery and failed attempts", "Earnings, history and incident reporting"] },
    { number: "04", label: "Provider or franchise portal", title: "Coordinate approved service partners.", text: "Allow merchants or franchise locations to manage relevant branches, teams, catalogues, availability and orders while central standards remain controlled.", image: "/services/app-development/1-slider/React Native App Development.png", alt: "Grocery merchant and franchise management portal", bullets: ["Merchant onboarding and approval", "Store profiles, zones and staff", "Catalogue, pricing and inventory", "Order and fulfilment settings", "Promotions, commissions and settlements", "Ratings, compliance and role-based access"] },
    { number: "05", label: "Admin dashboard", title: "Keep orders and fulfilment under control.", text: "Give catalogue, operations, support, finance and marketing teams central visibility with permissions matched to their responsibilities.", image: "/solutions/grocery/grocery-admin-analytics-dashboard.png", alt: "Grocery administration, inventory and dispatch dashboard", bullets: ["Real-time orders and delivery overview", "Customer, merchant, store and driver management", "Catalogue, inventory, zones and slots", "Pricing, promotions, payments and settlements", "Support, reviews and campaign content", "Reports, permissions, audit logs and integrations"] },
  ],
  technologyLead: "A grocery platform must coordinate accounts, products, inventory, orders, store operations, location data, payments and delivery updates reliably. We select the architecture according to expected order volume, catalogue size, integrations, data considerations and the long-term roadmap.",
  technologyImage: "/solutions/grocery/grocery-app-technology-integrations.png",
  technologyImageAlt: "Modern technology foundation for a grocery ordering and delivery platform",
  technologyTags: ["Flutter", "React Native", "Swift", "Kotlin", "React & Next.js", "Node.js", "Laravel", "Python", "REST & GraphQL", "PostgreSQL, MySQL & MongoDB", "AWS, Google Cloud & Azure", "Maps, payments, POS, ERP & notifications"],
  process: [
    ["Discovery and strategy", "Understand the business model, products, customers, stores, fulfilment locations, delivery teams, pricing, payments and growth objectives.", "A documented understanding of the proposed platform and operating requirements."],
    ["Research and planning", "Evaluate shopper expectations, fulfilment workflows, market conventions, operational dependencies and technical constraints, then prioritise the roadmap.", "A prioritised scope, recommended architecture and delivery plan."],
    ["UX and UI design", "Map journeys for shoppers, store teams, drivers, merchants, dispatchers and administrators before designing approved interfaces.", "An approved design system and interactive prototype."],
    ["Technical development", "Build the mobile apps, responsive web platform, team tools, merchant portal, dashboard, APIs and databases in planned stages.", "A working platform based on the agreed scope and interfaces."],
    ["Content and integrations", "Configure approved catalogues and pricing, then connect payments, maps, communications, analytics and compatible business systems.", "Coordinated content and functionality across approved third-party services."],
    ["Quality assurance", "Test functional, usability, catalogue, inventory, payment, ordering, location, access-control, API and performance requirements.", "A stable release candidate prepared for client review."],
    ["Testing and launch", "Configure production environments, app listings, analytics events, support processes and release settings.", "A production-ready grocery platform with launch requirements addressed."],
    ["Ongoing support", "Provide agreed monitoring, issue resolution, security updates, compatibility work, reporting and future functionality.", "Continued technical support as the grocery platform evolves."],
  ],
  detailSections: [
    {
      eyebrow: "Advanced capabilities", title: "More than a basic ordering application.", intro: "Advanced functionality can improve scheduling, repeat revenue, service quality and operating visibility. Features can be included in the initial release or phased according to business priorities and operational readiness.",
      items: [["Delivery zones and geofencing", "Define service areas, exclusions, distance limits, fees, minimum values and store eligibility."], ["Product substitutions", "Let customers approve, reject or predefine preferences for replacements with clear adjustments."], ["Weighted products", "Support estimated and final pricing for produce, meat, deli and other weight-based items."], ["Scheduled and express delivery", "Offer delivery options based on hours, capacity, order size and driver availability."], ["Route and dispatch support", "Allocate deliveries using driver availability, store location, capacity and time windows."], ["Dark-store and picking controls", "Coordinate fulfilment zones, picker assignments, order priority and packing stations."], ["Loyalty, wallet and referrals", "Encourage repeat purchasing with points, credits, codes, vouchers and memberships."], ["Multi-vendor basket logic", "Separate merchant fulfilment, charges, payments and settlements within a coherent experience."], ["Age-restricted product controls", "Apply appropriate restrictions or handover checks where legally required."], ["Automated offers and reminders", "Send relevant offers, basket reminders or reorder prompts according to permitted preferences."], ["Personalised reordering", "Help customers rebuild frequent baskets or reorder previous purchases."], ["Dynamic slot availability", "Adjust windows using store hours, picking capacity, drivers, routes and approved buffers."], ["Franchise and multi-branch management", "Separate catalogues, teams, pricing and reports while retaining group controls."], ["Marketplace provider management", "Onboard providers, define commissions, manage settlements and monitor quality."], ["AI-assisted operational features", "Use reviewed support, categorisation, scheduling or reporting tools with professional oversight."]],
    },
    {
      eyebrow: "Business benefits", title: "Create a better ordering and fulfilment experience.", intro: "A purpose-built platform creates a clear journey from product discovery to fulfilment. Sustainable value comes from technology working alongside accurate inventory, trained teams, realistic delivery promises and responsive service.",
      items: [["Generate more orders", "Clear products, reliable availability, visible delivery options and payment reduce purchase friction."], ["Improve customer convenience", "Customers can shop, schedule, pay, approve substitutions, track delivery and reorder."], ["Increase repeat revenue", "Saved baskets, loyalty, memberships and relevant offers support recurring relationships."], ["Use fulfilment capacity effectively", "Queues, picking status, slots, routes and updates help allocate staff and drivers."], ["Improve order accuracy", "Picking lists, item confirmation, substitutions and packing checks make quality measurable."], ["Reduce administrative work", "Automated confirmations, catalogue controls, payment status and reports replace fragmented tracking."], ["Support business purchasing", "Saved lists, scheduled orders, approvals, account billing and reports simplify B2B accounts."], ["Understand performance", "Dashboards reveal demand, availability, revenue, repeat orders and fulfilment quality."], ["Build direct relationships", "A branded platform provides control over communication, offers and first-party operational data."], ["Scale with greater control", "Add stores, teams, drivers, merchants, zones and accounts through structured permissions."]],
    },
    {
      eyebrow: "Industries and use cases", title: "Flexible solutions for grocery commerce businesses.", intro: "The platform can be configured around the way your organisation sells, fulfils and delivers retail products.",
      items: [["Supermarkets and hypermarkets", "Extend stores into digital ordering with branch catalogues, inventory, slots and promotions."], ["Independent grocery stores", "Give local retailers a branded ordering channel with manageable fulfilment tools."], ["Dark stores and quick commerce", "Coordinate high-volume picking, packing, stock, zones and rapid fulfilment."], ["Multi-branch grocery chains", "Manage products, prices, inventory, teams and performance across locations."], ["Multi-vendor grocery marketplaces", "Connect shoppers with approved merchants through central commercial and quality controls."], ["Organic and specialist retailers", "Present origin, dietary, certification or product-care information."], ["Fresh produce and farm delivery", "Support weighted products, seasonal availability, subscriptions and delivery schedules."], ["Convenience stores", "Offer fast discovery and delivery for daily essentials in local service zones."], ["Residential communities", "Support building instructions, concierge handovers, time windows and resident offers."], ["Office and business supplies", "Provide saved lists, repeat orders, approvals and account billing."], ["Pharmacy and personal care retail", "Offer approved product ranges subject to applicable licensing and rules."], ["Pet supplies and household essentials", "Build repeat-purchase journeys for care, cleaning and bulky products."], ["Wholesale and B2B grocery", "Support customer catalogues, minimum quantities, negotiated prices and distribution."], ["Franchise and cooperative networks", "Separate stores, catalogues, settlements and reports while retaining group standards."]],
    },
    {
      eyebrow: "Why Webtek Digital", title: "Built around your retail model—not a generic template.", intro: "We connect product strategy, user experience, engineering and growth planning around the practical realities of grocery commerce in Dubai, the UAE and the wider GCC.",
      items: [["Custom development", "Tailored to your products, stores, fulfilment teams, delivery model, pricing and brand."], ["Complete user ecosystem", "Customer apps, store portals, driver tools, merchant portals, admin systems and APIs."], ["Marketing-first thinking", "Discovery, conversion, CRM, referrals, retention and analytics are considered early."], ["UAE and GCC relevance", "Support for Arabic, regional payments, towers, gated access, zones and retail expectations."], ["Scalable architecture", "Structured for more users, stores, products, teams, merchants and integrations."], ["UX-focused design", "Each interface is planned around practical shopping, picking and delivery tasks."], ["Transparent project management", "Requirements, responsibilities, reviews and change requests stay documented."], ["Quality assurance", "Critical catalogue, checkout, inventory, payment and fulfilment journeys are tested."], ["End-to-end capability", "Strategy, branding, design, development, analytics, launch, marketing and maintenance."]],
    },
    {
      eyebrow: "Project investment", title: "How much does a grocery app cost?", intro: "Investment depends on the operating model, number of interfaces and feature complexity. We recommend a suitable first-release scope and provide a tailored proposal after consultation rather than a restrictive public package.",
      items: [["Product scope", "Customer, store, driver, merchant, administrator, iOS, Android and web requirements."], ["Catalogue and inventory", "Product volume, categories, attributes, variants and store-level availability."], ["Fulfilment", "Delivery zones, slots, routes, picking, substitutions and weighted products."], ["Commercial features", "Loyalty, memberships, business accounts, payments, refunds and settlements."], ["Platform complexity", "Branches, dark stores, marketplaces, languages, accessibility and target markets."], ["Integrations and data", "POS, ERP, inventory, logistics, migration, analytics and security."], ["Delivery and support", "Design, development, testing, launch and post-launch maintenance scope."]],
    },
    {
      eyebrow: "Free consultation", title: "Let’s discuss what you want to build.", intro: "The initial consultation helps establish which interfaces are needed, what the first release should include and how the platform can improve ordering and fulfilment. Your proposal will reflect the grocery platform your business actually requires.",
      items: [["Business model", "Revenue model, target shoppers and operating markets."], ["Fulfilment", "Single-store, multi-branch, dark-store or marketplace operations."], ["Products and operations", "Categories, pricing, inventory, teams, drivers, zones and capacity."], ["Growth features", "Substitutions, weighted items, loyalty, memberships and promotions."], ["Applications and systems", "Required apps, portals, payments, migration and integrations."], ["Delivery planning", "Initial priorities, target launch period, delivery approach and next steps."]],
    },
  ],
  faqTitle: "Grocery App Development FAQs",
  faqs: [
    ["What is a grocery app?", "A grocery app allows customers to browse products, build a basket, select delivery or collection, pay and follow order progress. A complete solution can also include store, fulfilment, driver, merchant and administration tools."],
    ["Can Webtek Digital build a custom grocery app in Dubai?", "Yes. Catalogues, stores, inventory, fulfilment, delivery, payments and integrations can be tailored for businesses in Dubai and across the UAE."],
    ["Can the app support one store and multiple branches?", "Yes. The platform can support one supermarket, several branches, dark stores or a merchant network, with catalogue, price, availability and delivery settings by location."],
    ["Which applications and portals are included?", "A solution may include a customer app, responsive ordering website, store and fulfilment portal, delivery-partner app, merchant portal, administration dashboard and marketing website. The final combination follows discovery."],
    ["Can the platform show store-level inventory?", "Yes. Availability can be maintained through store controls, imports or compatible integrations. Real-time reliability depends on the quality and frequency of the underlying data."],
    ["Can customers approve product substitutions?", "Yes. Customers can set replacement preferences and approve or reject proposed substitutions with quantity and price changes shown before the order proceeds."],
    ["Can delivery partners receive and update orders?", "Yes. Driver apps can provide requests, collection details, navigation, statuses, customer communication, proof of delivery and earnings history."],
    ["Can the platform support a multi-vendor grocery marketplace?", "Yes. Merchants can maintain separate stores, catalogues, prices, availability and fulfilment settings while administrators manage commissions, settlements, zones and quality."],
    ["Can business customers place recurring grocery orders?", "Yes. Business accounts can include authorised users, saved lists, recurring schedules, approvals, account billing and customer-level reporting."],
    ["Can customers track deliveries in real time?", "Potentially. Driver location and estimated-arrival updates can be included where appropriate; accuracy depends on permissions, connectivity, mapping services and workflow."],
    ["Which payment methods can be included?", "Depending on provider and market, options may include cards, Apple Pay, Google Pay, cash, account credit or corporate invoicing. Recurring billing depends on gateway capability and merchant eligibility."],
    ["Can the application support English and Arabic?", "Yes. English and Arabic interfaces can be developed, including right-to-left layouts, with other languages considered for the target market."],
    ["Can existing product and customer data be migrated?", "Potentially. Feasibility depends on data quality, format, ownership and export options and must be assessed before scope is confirmed."],
    ["How long does development take?", "Timing depends on interface count, design scope, feature complexity, integrations, migration, testing and approval speed. A detailed schedule follows discovery."],
    ["Do you provide maintenance after launch?", "Yes. Support can cover monitoring, issue resolution, compatibility, security and dependency updates, reporting and future development under a separate agreement."],
    ["Will the platform support Google Ads and Meta campaigns?", "Relevant websites can be configured for GA4, Google Tag Manager and Meta Pixel conversion tracking, with mobile attribution planned as required."],
    ["Can the platform support weighted products?", "Yes. It can show an estimated price and update the final amount using confirmed weight, subject to the retailer’s measurement, payment and approval workflow."],
    ["Can the app support loyalty points and memberships?", "Yes. Loyalty points, referral credits, member prices, delivery subscriptions and other approved benefits can be included according to commercial rules and provider capabilities."],
  ],
  cta: { eyebrow: "Planning a grocery platform?", title: "Build a grocery experience customers return to.", body: "Tell us about your catalogue, stores, fulfilment model, delivery areas and growth objectives. We’ll help define the shopper, store, driver, merchant and administration experiences you need.", href: "mailto:info@webtekdigital.com?subject=Grocery app development enquiry" },
});

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: config.faqs?.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })),
};

export default function Page() {
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema).replace(/</g, "\\u003c") }} /><CloneAppTemplate config={config} /></>;
}
