import type { Metadata } from "next";
import { CloneAppTemplate } from "../../components/solutions/CloneAppTemplate";
import { createStandardSolutionConfig } from "../../components/solutions/StandardSolutionPage";

export const metadata: Metadata = { title: "Grocery App Development Dubai | Webtek Digital", description: "Custom grocery delivery app development for businesses in Dubai and the UAE." };
const config = createStandardSolutionConfig({
  eyebrow: "Grocery delivery platform", title: "Grocery app development in Dubai", lead: "Build a convenient grocery-shopping experience with fast ordering, dependable fulfilment and complete control over your catalogue and delivery operation.",
  overview: ["A grocery platform connects shoppers, stores, inventory, fulfilment teams, delivery partners and administrators through one coordinated ecosystem.", "We configure it around your product catalogue, delivery promise, service zones and commercial model."], metrics: [["4", "connected user products"], ["1", "central operations hub"], ["24/7", "customer ordering"]],
  features: [["Product discovery", "Organise categories, search, favourites and product details for quick shopping."], ["Smart checkout", "Offer delivery slots, substitutions, secure payments and saved addresses."], ["Inventory controls", "Maintain pricing, stock and availability with store-side tools."], ["Order fulfilment", "Coordinate picking, packing and order handover in real time."], ["Live delivery", "Keep shoppers informed with order notifications and driver tracking."], ["Growth tools", "Run offers, loyalty programmes and reporting from one place."]],
  modules: [{ number: "01", label: "Shopper app", title: "Everyday groceries, effortlessly ordered.", text: "Customers browse products, select a delivery slot, pay securely and follow their order to the door.", image: "/solutions/talabat/An intuitive experience that drives repeat orders..png", alt: "Grocery customer app" }, { number: "02", label: "Store console", title: "Practical tools for store and fulfilment teams.", text: "Manage products, stock, orders, substitutions, promotions and fulfilment progress.", image: "/solutions/talabat/Independent controls for every restaurant..png", alt: "Grocery store console" }, { number: "03", label: "Operations hub", title: "Visibility across the full grocery operation.", text: "Oversee stores, orders, delivery zones, customers, payments and reporting.", image: "/solutions/talabat/Manage the entire marketplace in one place..png", alt: "Grocery operations dashboard" }],
  technologyLead: "Your platform can be built for reliable commerce, real-time inventory and flexible expansion into new stores and areas.", technologyTags: ["iOS and Android", "Store dashboard", "Secure APIs", "Cloud deployment", "Payment integration", "Maps and notifications"], process: [["Discovery & strategy", "Define your catalogue, fulfilment model and delivery promise."], ["UX/UI design", "Design simple customer, store and delivery workflows."], ["Development", "Build connected commerce and operations experiences."], ["Testing & launch", "Validate ordering, inventory and fulfilment flows before launch."]], cta: { eyebrow: "Ready to launch a grocery app?", title: "Build a grocery experience customers return to.", body: "Talk to us about a grocery delivery platform designed around your business.", href: "mailto:info@webtekdigital.com?subject=Grocery app development enquiry" },
});
export default function Page() { return <CloneAppTemplate config={config} />; }
