import type { Metadata } from "next";
import { CloneAppTemplate, type CloneAppTemplateConfig } from "../../components/solutions/CloneAppTemplate";

export const metadata: Metadata = {
  title: "Home Maintenance App Development Dubai | Webtek Digital",
  description: "Build a custom home maintenance app in Dubai with customer booking, technician, operations and admin solutions developed by Webtek Digital.",
};

const config: CloneAppTemplateConfig = {
  eyebrow: "Home services and field-service platform development",
  title: "Home Maintenance App Development in Dubai",
  lead: "Launch a custom home services platform built around the way your maintenance business operates. We develop scalable applications that connect customers, technicians, operations teams and administrators through one coordinated digital ecosystem.",
  primaryCta: "Discuss Your App",
  secondaryCta: "Request a Consultation",
  heroImage: "/solutions/talabat/talabat.png",
  heroImageAlt: "Home maintenance app development solution for service businesses in Dubai",
  overview: ["A professional home maintenance solution connects customers, technicians, service managers, payments and support teams through one reliable operating system. Customers can request help and follow progress, while field teams have accurate job information, practical schedules and simple status controls.", "Webtek Digital develops each part around your service catalogue, coverage areas, workforce model, pricing method and approval process. The system can support employed technicians, contractors, external vendors or a blended network across residential, commercial and property-management operations."],
  metrics: [["3+", "connected user interfaces"], ["1", "central service operations system"], ["24/7", "booking and job visibility"]],
  features: [
    ["Service discovery", "Organise categories, property types, urgency, coverage, specialist needs, service inclusions, indicative pricing and verified feedback."],
    ["Instant and scheduled booking", "Support urgent requests, future appointments, recurring schedules, property details, images, access instructions and reminders."],
    ["Technician tools", "Provide schedules, job details, navigation, checklists, before-and-after evidence, material records and simple completion controls."],
    ["Smart assignment", "Match service requests by location, availability, skills, service category, certification, workload and configurable priorities."],
    ["Digital quotations", "Enable itemised labour, material and tax quotations with digital approval, rejection and clarification workflows."],
    ["Operations controls", "Manage services, zones, technician capacity, vendors, pricing, payments, support, quality and reporting from one dashboard."],
  ],
  modules: [
    { number: "01", label: "Customer app", title: "Book home services without the back-and-forth.", text: "Customers can discover services, manage apartment or villa profiles, book instantly or in advance, upload images, request quotations, see technician updates, pay, rebook, view invoices and manage ratings, warranties and support.", image: "/solutions/talabat/An intuitive experience that drives repeat orders..png", alt: "Customer home maintenance booking application interface" },
    { number: "02", label: "Technician app", title: "Clear job details for field teams.", text: "Technicians can manage availability, receive assignments, navigate to properties, check in, follow digital checklists, record labour and parts, submit quotations, capture evidence and complete work with customer confirmation.", image: "/solutions/talabat/Keep delivery partners moving efficiently..png", alt: "Technician job schedule and service details application" },
    { number: "03", label: "Vendor portal", title: "Manage external service partners with defined controls.", text: "Approved contractors can manage technicians, categories, availability, documents, allocated work, quotations, status, invoices and performance while the platform retains central oversight.", image: "/solutions/talabat/Independent controls for every restaurant..png", alt: "Home services contractor and vendor management portal" },
    { number: "04", label: "Admin dashboard", title: "One view across service delivery.", text: "Teams can oversee bookings, customers, properties, technicians, vendors, capacity, quotations, fees, payments, contracts, support, quality reviews, reports and role-based permissions.", image: "/solutions/talabat/Manage the entire marketplace in one place..png", alt: "Home maintenance operations and administration dashboard" },
  ],
  technologyLead: "A home maintenance platform must coordinate customer requests, schedules, field activity, media uploads, payments and operational records without becoming difficult to maintain. We select the architecture around service complexity, integration needs, data considerations and the long-term roadmap.",
  technologyImage: "/solutions/talabat/%20teck-stacks%20.png",
  technologyImageAlt: "Scalable technology stack for a home maintenance application",
  technologyTags: ["Flutter or React Native", "Swift and Kotlin", "React and Next.js", "Node.js / Laravel / Python", "Secure REST or GraphQL APIs", "PostgreSQL / MySQL / MongoDB", "AWS / Google Cloud / Azure", "Maps, payments and notifications", "CRM, ERP and accounting integrations", "Secure media and document storage"],
  process: [["Discovery", "Understand the service model, customers, catalogue, coverage areas, workforce, booking process, pricing and operational issues."], ["Research and planning", "Evaluate customer expectations and field-service workflows, then prioritise the initial release and roadmap."], ["UX and UI design", "Map journeys for customers, technicians, vendors, dispatchers, support teams and administrators."], ["Technical development", "Build the applications, portals, dashboard, APIs, database and notification services in planned stages."], ["Integrations", "Connect payment, mapping, communication, CRM, accounting, support and other approved systems."], ["Quality assurance", "Test functional, usability, payment, location, API, access-control and performance journeys across supported environments."], ["Testing and launch", "Configure production, app listings, analytics, support processes and release settings for launch."], ["Ongoing support", "Provide monitoring, issue resolution, compatibility and security updates, reporting and future feature development."]],
  detailSections: [
    { eyebrow: "Advanced capabilities", title: "More than a basic booking application.", intro: "Advanced features can improve service accuracy, repeat business, technician productivity and operational visibility in the first release or as future phases.", items: [["Annual maintenance contracts", "Manage covered properties, included services, visit frequency, limits, renewals and entitlements."], ["Recurring service plans", "Create automatic schedules and reminders for cleaning, AC servicing, pest control, landscaping or pool care."], ["Inventory and warranty management", "Track parts and stock, connect use to job costs, and manage covered revisits and rectification."], ["Multi-property and corporate accounts", "Provide property records, users, budgets, approval workflows, statements and service-level reporting."], ["Service quality controls", "Use mandatory checklists, evidence, customer confirmation, supervisor review and escalation rules."], ["IoT and property integrations", "Connect smart devices, building systems or sensors to preventive maintenance and service alerts where suitable APIs exist."]] },
    { eyebrow: "Business benefits", title: "Turn service operations into a more connected customer experience.", intro: "A purpose-built platform creates one structured journey from the first request to final service confirmation, making performance easier to manage and customer expectations easier to meet.", items: [["Generate more bookings", "Make services, requirements and appointments easier to understand and reserve."], ["Reduce manual coordination", "Replace fragmented spreadsheets, calls and chat groups with structured requests, assignments and live statuses."], ["Increase technician productivity", "Give field teams clear schedules, property details, navigation, checklists and evidence capture."], ["Strengthen trust and quality", "Use updates, profiles, invoices, history, signatures, reviews and complaint workflows."], ["Support repeat revenue", "Enable annual contracts, recurring services, reminders, customer credit and rebooking."], ["Gain operational visibility", "Monitor demand, capacity, response times, cancellations, revenue, quality and workforce performance."]] },
    { eyebrow: "Industries and use cases", title: "Flexible solutions for service and property businesses.", intro: "The platform can be adapted to the operating model, approved service catalogue and customer group involved.", items: [["Home maintenance and handyman marketplaces", "Coordinate residential bookings, technicians, quotations, invoices, providers, ratings and support."], ["Facilities and property management", "Manage planned and reactive work across properties, tenants, landlords, contractors and client accounts."], ["Developers and hospitality", "Support post-handover defects, warranty requests, guest issues, cleaning, inspections and repairs."], ["Commercial and multi-branch businesses", "Route requests by site, department, priority and approval level with central reporting."], ["Specialist service providers", "Adapt processes for AC, plumbing, electrical, cleaning, pest control, landscaping, appliance repair or pool care."], ["AMC and institutional facilities", "Manage entitlements, periodic visits, controlled roles, documentation and integration requirements."]] },
    { eyebrow: "Why Webtek Digital", title: "Built around your operations—not a generic script.", intro: "We tailor the platform to your services, workforce, coverage, approvals and brand, then support the product from strategy through launch and enhancement.", items: [["Complete user ecosystem", "Customer and technician apps, vendor and business portals, dashboard, APIs and websites."], ["UAE and GCC relevance", "Account for Arabic interfaces, regional payments, property-management needs and local operating models."], ["Marketing-first thinking", "Plan acquisition, conversion tracking, referrals, retention and analytics alongside the product."], ["Scalable architecture", "Prepare for additional users, vendors, services, branches, properties, markets and integrations."], ["UX-focused design", "Build each interface around practical tasks, from booking to evidence capture and quotation approval."], ["Transparent delivery", "Keep requirements, deliverables, reviews, responsibilities and quality assurance clearly documented."]] },
    { eyebrow: "Project investment", title: "How much does a home maintenance app cost?", intro: "Investment depends on the operating model, applications required and workflow complexity. A focused booking solution differs significantly from a multi-vendor marketplace across several cities and service categories.", items: [["Interfaces and channels", "Customer, technician, vendor and admin products across iOS, Android and responsive web."], ["Booking and operations", "Catalogue, scheduling, capacity, assignment, quotations, approvals, contracts and recurring services."], ["Commercial workflows", "Payments, invoices, refunds, settlements, commissions, customer accounts and warranties."], ["Launch readiness", "Languages, integrations, design, data migration, reporting, security, testing and post-launch support."]] },
  ],
  faqTitle: "Home Maintenance App Development FAQs",
  faqs: [["What is a home maintenance app?", "It is a digital platform for finding, requesting, scheduling and paying for property services, often with technician, vendor and admin tools for operational management."], ["Can Webtek Digital build a custom home maintenance app in Dubai?", "Yes. The catalogue, customer journey, workforce model, pricing, coverage and integrations can be tailored for a business in Dubai and across the UAE."], ["Which services can be offered through the app?", "Approved categories can include AC maintenance, plumbing, electrical work, cleaning, painting, carpentry, pest control, landscaping, pool care, appliance repair and handyman services."], ["Can customers book emergency and scheduled services?", "Yes. The platform can support immediate, future and recurring bookings with rules based on location, capacity, working hours and service category."], ["Can technicians receive and update jobs from their phones?", "Yes. The technician app can provide job details, navigation, checklists, evidence, quotation requests, status controls and completion confirmation."], ["Can the platform support multiple vendors?", "Yes. Approved providers can manage their own teams, availability, jobs and settlement information while the administrator retains control."], ["Can customers approve quotations digitally?", "Yes. Technicians or estimators can submit itemised quotations for customer or manager approval before further work begins."], ["Can annual maintenance contracts be managed?", "Yes. AMC features can manage properties, periods, included services, visits, limits, renewals and service history."], ["Can the application support English and Arabic?", "Yes. English and Arabic interfaces, including right-to-left Arabic layouts, can be developed along with other languages where required."], ["Can the app integrate with CRM, ERP or accounting systems?", "Potentially. Feasibility depends on each system’s API, documentation, security conditions and commercial access."], ["Do you provide maintenance after launch?", "Yes. Ongoing support can cover monitoring, issue resolution, compatibility and security updates, reporting and future development."], ["Will the platform support Google Ads and Meta campaigns?", "Relevant landing pages can be configured for GA4, Google Tag Manager and Meta Pixel conversion tracking; mobile attribution can also be planned."]],
  cta: { eyebrow: "Build a better way to manage home services.", title: "Let’s discuss what you want to build.", body: "Tell us about your services, target locations, workforce model and operating requirements. We will help define the customer, technician, vendor and administration experiences needed to move forward.", href: "mailto:info@webtekdigital.com?subject=Home maintenance app development consultation" },
};

export default function Page() { return <CloneAppTemplate config={config} />; }
