import type { Metadata } from "next";
import { CloneAppTemplate } from "../../components/solutions/CloneAppTemplate";
import { createStandardSolutionConfig } from "../../components/solutions/StandardSolutionPage";
export const metadata: Metadata = { title: "Ecommerce App Development Dubai | Webtek Digital", description: "Custom ecommerce app development for ambitious retail businesses in Dubai and the UAE." };
const config = createStandardSolutionConfig({
  eyebrow: "Mobile commerce platform", title: "Ecommerce app development in Dubai", lead: "Turn your retail business into a high-performing mobile shopping experience built to convert, retain and grow.", overview: ["A branded ecommerce app brings product discovery, checkout, fulfilment, customer service and marketing into one polished customer journey.", "We design the platform around your catalogue, brand, fulfilment model and growth goals."], metrics: [["2", "connected user products"], ["1", "commerce control centre"], ["24/7", "shopping access"]],
  features: [["Product catalogue", "Create rich collections, filters, search and product-detail experiences."], ["Fast checkout", "Make buying easy with saved details, secure payments and flexible delivery."], ["Customer accounts", "Give customers wishlists, order history, returns and profile controls."], ["Inventory management", "Maintain products, variants, pricing and stock from a central workspace."], ["Promotions", "Support discount codes, bundles, loyalty and targeted offers."], ["Commerce insights", "Measure sales, product performance, conversion and customer activity."]], modules: [{ number: "01", label: "Shopping app", title: "A storefront customers enjoy using.", text: "Create a fast, on-brand path from product discovery to secure checkout.", image: "/solutions/talabat/An intuitive experience that drives repeat orders..png", alt: "Ecommerce shopping app" }, { number: "02", label: "Commerce dashboard", title: "Control your digital store with confidence.", text: "Manage products, orders, fulfilment, customers, promotions and reports in one place.", image: "/solutions/talabat/Manage the entire marketplace in one place..png", alt: "Ecommerce dashboard" }], technologyLead: "A scalable commerce foundation helps you deliver a consistent brand experience and support future growth.", technologyTags: ["iOS and Android", "Ecommerce dashboard", "Secure APIs", "Cloud deployment", "Payment integration", "Analytics"], process: [["Discovery & strategy", "Define your products, customers and fulfilment model."], ["UX/UI design", "Create a high-converting shopping journey around your brand."], ["Development", "Build the customer and commerce-management experiences."], ["Testing & launch", "Validate catalogue, checkout and post-purchase journeys."]], cta: { eyebrow: "Planning a mobile commerce app?", title: "Let’s create a store your customers carry with them.", body: "We can build an ecommerce platform tailored to your retail operation.", href: "mailto:info@webtekdigital.com?subject=Ecommerce app development enquiry" },
});
export default function Page() { return <CloneAppTemplate config={config} />; }
