import type { Metadata } from "next";
import { CloneAppTemplate, type CloneAppTemplateConfig } from "../../components/solutions/CloneAppTemplate";

export const metadata: Metadata = {
  title: "E-learning App Development Dubai | Webtek Digital",
  description:
    "Build a custom e-learning app in Dubai with learner, instructor, course management and admin solutions developed by Webtek Digital.",
};

const config: CloneAppTemplateConfig = {
  eyebrow: "Custom learning platforms",
  title: "E-learning App Development in Dubai",
  lead: "Create a branded learning platform that connects learners, educators, course managers and administrators through one coordinated digital ecosystem. Whether you are launching an online academy, digitising classroom programmes or building a course marketplace, we develop an original solution around your content, audience and commercial goals.",
  primaryCta: "Discuss Your App",
  secondaryCta: "Explore the Platform",
  heroImage: "/talabat/banner-wel.png.webp",
  heroImageAlt: "E-learning app development solution for education and training businesses in Dubai",
  overview: [
    "A professional e-learning solution brings learners, educators, courses, progress tracking and support into one connected system. Learners receive a clear route from registration to completion, instructors gain practical teaching tools, and administrators maintain visibility across enrolments, payments, engagement and platform quality.",
    "Webtek Digital develops each component around your learning model, target audience, content structure, certification requirements and revenue approach. The platform can support self-paced courses, instructor-led programmes, blended learning, live classes, memberships, institutional training or a multi-vendor education marketplace.",
  ],
  metrics: [
    ["3+", "connected learner, instructor and administration experiences"],
    ["1", "central system for content, users, payments and reporting"],
    ["24/7", "access to approved learning and progress information"],
  ],
  features: [
    ["Course catalogue", "Organise programmes by subject, level, instructor, format, duration, language and audience, with clear outcomes, prerequisites, curriculum previews and access options."],
    ["Learning journeys", "Structure courses into modules, lessons and activities with progress indicators, prerequisites, scheduled release, learning paths, reminders and completion rules."],
    ["Instructor tools", "Give educators role-based controls for course creation, content uploads, assessments, cohorts, announcements, learner feedback, grading and course analytics."],
    ["Assessments", "Create quizzes, examinations and assignments using reusable question banks, randomisation, time limits, scoring rules, manual grading and feedback."],
    ["Live learning", "Schedule instructor-led sessions through suitable virtual-classroom technology, supported by reminders, attendance records and session resources."],
    ["Learning analytics", "Monitor enrolments, lesson activity, completion, assessment results, learner drop-off, ratings, instructor performance and revenue through appropriate dashboards."],
  ],
  modules: [
    {
      number: "01",
      label: "Learner app",
      title: "Make learning easy to start and continue.",
      text: "Give learners one focused place to discover and enrol in courses, watch or read lessons, join live sessions, submit work, receive feedback, track progress and access certificates. The experience can support iOS, Android and responsive web, with English, Arabic and selected offline content where appropriate.",
      image: "/talabat/customer-panel.png.webp",
      alt: "Mobile learner application with course discovery and progress features",
    },
    {
      number: "02",
      label: "Instructor portal",
      title: "Simple controls for course creators.",
      text: "Provide instructors with a structured workspace for building curricula, uploading resources, creating quizzes and assignments, managing cohorts, scheduling live sessions, reviewing submissions, grading learners and understanding engagement.",
      image: "/talabat/app-screen3.png.webp",
      alt: "Instructor portal for creating courses and monitoring learners",
    },
    {
      number: "03",
      label: "Organisation portal",
      title: "Control learning across teams and institutions.",
      text: "Help HR, L&D and institutional managers enrol users in bulk, organise groups and departments, assign role-based learning paths, set deadlines, monitor compliance, review certificate status and export account-level reports.",
      image: "/talabat/all-language.webp",
      alt: "Organisation training portal for team enrolment and reporting",
    },
    {
      number: "04",
      label: "Admin dashboard",
      title: "Manage the learning operation in one place.",
      text: "Maintain central control over learners, instructors, organisations, courses, content approvals, enrolments, assessments, certificates, pricing, payments, support, permissions, reporting, integrations and audit history.",
      image: "/talabat/banner-wel.png.webp",
      alt: "E-learning administration dashboard for courses, users and reporting",
    },
  ],
  technologyLead: "An e-learning platform must deliver media, track progress, manage access and process user activity reliably across devices and locations. We select the architecture according to course volume, audience scale, content formats, live-learning requirements, security considerations and the long-term product roadmap.",
  technologyImage: "/talabat/all-language.webp",
  technologyImageAlt: "Modern technology foundation for a scalable e-learning platform",
  technologyTags: [
    "Flutter or React Native",
    "Swift and Kotlin",
    "React and Next.js",
    "Node.js, Laravel or Python",
    "REST or GraphQL APIs",
    "PostgreSQL, MySQL or MongoDB",
    "Secure media delivery",
    "AWS, Google Cloud or Azure",
    "Payments and notifications",
    "Video classroom integrations",
    "CRM, HRIS and SSO",
    "Analytics and monitoring",
  ],
  process: [
    ["Discovery", "Define the learning model, audience, course structure, instructor roles, content formats, certification needs, revenue approach and business objectives."],
    ["Research and planning", "Evaluate learner expectations, educator workflows, market conventions, technical dependencies and content operations before prioritising the first release."],
    ["UX and UI design", "Map journeys for learners, instructors, organisation managers and administrators, then create an approved design system and interactive prototype."],
    ["Technical development", "Build the agreed mobile apps, responsive web experience, portals, dashboard, APIs, databases and learning services in planned stages."],
    ["Content and integrations", "Configure or migrate approved course content and connect the required payment, video, communication, analytics, identity and business systems."],
    ["Quality assurance", "Test functionality, usability, media, assessments, payments, access controls, APIs and performance across supported devices and browsers."],
    ["Testing and launch", "Prepare production environments, application listings, analytics events, support processes and release settings for launch."],
    ["Ongoing support", "Support monitoring, issue resolution, security and dependency updates, operating-system compatibility, reporting and future enhancements."],
  ],
  detailSections: [
    {
      eyebrow: "Advanced capabilities",
      title: "More than a basic course library.",
      intro: "Advanced functionality can improve engagement, assessment, personalisation, institutional control and commercial growth. Features can be included in the first release or introduced through a phased roadmap.",
      items: [
        ["Certificates and credentials", "Issue branded certificates when defined completion, attendance or assessment conditions are met, with verification options where required."],
        ["Cohorts and communities", "Organise scheduled learner groups around shared dates, discussions, announcements, deadlines and instructor support."],
        ["Learning paths", "Combine courses and activities into structured programmes for job roles, qualifications, onboarding or skill development."],
        ["Subscriptions and memberships", "Offer monthly or annual access to eligible content, communities, live sessions and member benefits."],
        ["Course marketplace", "Allow approved instructors or institutions to publish courses under review, with creator profiles, commissions, settlements and ratings."],
        ["Gamification", "Encourage suitable learning behaviours through points, badges, streaks, milestones, leaderboards or challenges."],
        ["Personalised learning", "Use learner choices, progress, results or configured rules to recommend relevant content and next steps."],
        ["Multilingual and RTL", "Deliver interfaces and course content in English, Arabic and other languages, including right-to-left layouts."],
        ["Offline learning", "Allow selected content to be downloaded securely for temporary offline use, subject to rights and synchronisation requirements."],
        ["Content protection", "Apply authenticated access, streaming controls, watermarking or download restrictions according to the content model."],
        ["Proctoring and identity", "Connect suitable identity or remote-proctoring services for controlled assessments where proportionate and legally permitted."],
        ["AI-assisted features", "Consider carefully reviewed content search, study support, question suggestions or administrative automation with privacy controls and human oversight."],
      ],
    },
    {
      eyebrow: "Business benefits",
      title: "Create a stronger learning and training experience.",
      intro: "A purpose-built platform creates a structured route from discovery to completion while giving educators and administrators clearer operational control. Technology provides the infrastructure; course quality, instructional design, educator support and continuous improvement remain essential.",
      items: [
        ["Expand learning access", "Make approved programmes available across locations and devices without requiring every learner to attend one physical venue."],
        ["Create new revenue", "Sell individual courses, bundles, subscriptions, memberships, live programmes or institutional access."],
        ["Improve convenience", "Give learners one place for content, lessons, submissions, live sessions, feedback and certificates."],
        ["Reduce administration", "Use automated enrolment, notifications, tracking, certificates and reporting to reduce repetitive manual work."],
        ["Support consistent delivery", "Maintain clearer standards through structured curricula, publishing workflows, reusable assessments and permissions."],
        ["Understand engagement", "Identify where learners enrol, participate, progress, struggle or leave to guide practical improvements."],
        ["Strengthen brand ownership", "Control the brand, learning journey, customer relationship and future functionality beyond a generic marketplace presence."],
        ["Serve organisations at scale", "Use group enrolment, manager portals, learning paths and account reporting for enterprise and institutional clients."],
        ["Build lasting relationships", "Support repeat participation through recommendations, alerts, memberships, communities and continued access."],
        ["Scale with control", "Add courses, instructors, cohorts, organisations, languages and integrations through structured permissions."],
      ],
    },
    {
      eyebrow: "Industries and use cases",
      title: "Flexible learning solutions for different organisations.",
      intro: "The platform structure, permissions and learning journeys can be adapted to the audience, governance requirements and delivery model of each organisation.",
      items: [
        ["Schools and education groups", "Support supplementary learning, assignments, resources and progress visibility across classes and campuses."],
        ["Universities", "Deliver continuing education, blended programmes, short credentials and alumni learning."],
        ["Training institutes", "Sell and deliver self-paced, live or blended programmes with assessments and certification."],
        ["Corporate L&D", "Assign onboarding, compliance, product, leadership and skills training by role, department or location."],
        ["Healthcare education", "Provide controlled professional training, policy learning and continuing development with appropriate governance."],
        ["Real estate and construction", "Deliver sales, compliance, safety, technical and operational learning for field teams and partners."],
        ["Hospitality and retail", "Standardise onboarding, customer service, product knowledge and brand training across branches."],
        ["Professional services", "Manage technical learning, certification preparation, compliance and continuing professional development."],
        ["Government and public sector", "Support role-based programmes, multilingual content, controlled access and authorised reporting."],
        ["Professional associations", "Provide member education, webinars, qualifications, development records and paid learning benefits."],
        ["Independent academies", "Build a direct-to-learner business with courses, communities, payments and memberships."],
        ["Course marketplaces", "Connect learners with approved educators through a centrally managed catalogue and quality process."],
        ["Customer education", "Help technology and service businesses train customers, resellers and partners."],
        ["Language and exam preparation", "Combine structured lessons, practice activities, live teaching, assessments and progress tracking."],
      ],
    },
    {
      eyebrow: "Why Webtek Digital",
      title: "Built around your learning model—not a generic template.",
      intro: "We connect product strategy, user experience, engineering and digital growth so the learning platform reflects both educational operations and commercial goals.",
      items: [
        ["Custom development", "Tailor the platform to your audience, content, teaching approach, commercial model and brand."],
        ["Complete user ecosystem", "Develop learner apps, instructor portals, organisation dashboards, administration systems, APIs and marketing websites."],
        ["Marketing-first thinking", "Consider course discovery, enrolment conversion, analytics, CRM integration and retention during product planning."],
        ["UAE and GCC relevance", "Plan for Arabic interfaces, regional payments, institutional buyers and multilingual audiences."],
        ["Scalable architecture", "Structure the solution for additional users, organisations, courses, languages, markets and integrations."],
        ["UX-focused design", "Plan every interface around practical tasks, from starting a lesson to reviewing organisation-wide completion."],
        ["Transparent delivery", "Document requirements, deliverables, responsibilities, reviews and change requests throughout development."],
        ["Quality assurance", "Review enrolment, learning, assessment, payment, reporting and administration journeys before release."],
        ["End-to-end capability", "Support strategy, branding, UI/UX, development, integrations, analytics, launch, marketing and maintenance."],
      ],
    },
    {
      eyebrow: "Project investment",
      title: "How much does an e-learning app cost?",
      intro: "Cost depends on the learning model, number of interfaces and complexity of the required features. After an initial consultation, we recommend an appropriate first-release scope and provide a tailored proposal rather than forcing different learning operations into a fixed package.",
      items: [
        ["Applications and platforms", "Scope varies according to learner, instructor, organisation and admin interfaces across iOS, Android and responsive web."],
        ["Learning complexity", "Course structures, media delivery, assessments, grading, certificates, cohorts and live classes shape the investment."],
        ["Commercial model", "Payments, subscriptions, bundles, refunds, institutional access and instructor settlements introduce different requirements."],
        ["Access and content", "Languages, accessibility, offline learning, content protection and migration affect design and engineering scope."],
        ["Integrations and operations", "Existing systems, analytics, security, performance, launch requirements and post-launch support are assessed during discovery."],
      ],
    },
    {
      eyebrow: "Free consultation",
      title: "Let’s discuss what you want to build.",
      intro: "Speak with Webtek Digital about your learning concept, target users, content, delivery model and commercial objectives. The initial consultation helps define the interfaces, first-release priorities and delivery approach.",
      items: [
        ["Learning model", "Discuss target learners, operating markets, course structure, content formats and revenue objectives."],
        ["Teaching requirements", "Review instructor roles, assessments, certificates, live learning, cohorts and accessibility."],
        ["Access and commerce", "Define payment, subscription, organisation access, languages and permissions."],
        ["Technical scope", "Identify required applications, portals, content migration, integrations, launch priorities and next steps."],
      ],
    },
  ],
  faqTitle: "E-learning App Development FAQs",
  faqs: [
    ["What is an e-learning app?", "An e-learning app allows learners to access courses, lessons, assessments, live sessions, progress information and certificates. A complete solution can also include instructor tools, organisation portals and a central administration dashboard."],
    ["Can Webtek Digital build a custom e-learning app in Dubai?", "Yes. We can develop a custom learning platform for businesses, academies and institutions in Dubai and across the UAE, tailored to the audience, teaching model, content, commercial structure and required integrations."],
    ["Which applications and portals are included?", "A solution may include a learner mobile app, responsive learner website, instructor portal, organisation or training-manager portal, administration dashboard and marketing website. The final combination is confirmed after discovery."],
    ["Can the platform support self-paced and live courses?", "Yes. It can combine on-demand lessons, scheduled live classes, cohorts, assignments, discussions and instructor feedback according to the programme design."],
    ["Can instructors create and manage their own courses?", "Yes. Approved instructors can receive role-based tools for curricula, uploads, quizzes, assignments, communication, grading and analytics, with administrator review where required."],
    ["Can the app sell courses and subscriptions?", "Yes. Depending on the payment provider and business model, the platform can support course purchases, bundles, memberships, recurring subscriptions, coupons and institutional access."],
    ["Can certificates be generated automatically?", "Yes. Branded certificates can be issued when configured completion, attendance or assessment conditions are met. Verification functionality can also be considered."],
    ["Can the platform support corporate training?", "Yes. Corporate features can include bulk enrolment, departments, role-based learning paths, deadlines, manager dashboards, compliance tracking and organisation-level reports."],
    ["Can learners access courses offline?", "Selected content can potentially be downloaded for controlled offline access. The scope depends on content rights, media formats, storage, security and synchronisation requirements."],
    ["Can the application support English and Arabic?", "Yes. English and Arabic interfaces can be developed, including right-to-left support. Course content can also be organised by language."],
    ["Can the platform integrate with virtual classroom tools?", "Potentially. Integration with Zoom, Teams or another provider depends on its available API, licensing, documentation and the intended learning workflow."],
    ["Can existing course content be migrated?", "Yes, subject to format, quality, ownership and volume. The source system and available export options must be assessed before migration scope is confirmed."],
    ["How long does development take?", "The timeline depends on the interfaces, design scope, content readiness, feature complexity, integrations, testing and approval speed. A detailed schedule is prepared after discovery."],
    ["Do you provide maintenance after launch?", "Yes. Support can include monitoring, issue resolution, compatibility updates, security and dependency updates, reporting and future development under an agreed arrangement."],
    ["Will the platform support Google Ads and Meta campaigns?", "Relevant websites and landing pages can be configured for analytics and conversion tracking through tools such as Google Analytics 4, Google Tag Manager and Meta Pixel. Mobile attribution can also be planned."],
    ["Can AI features be added to the learning platform?", "Potentially. AI-assisted search, learner support, recommendations or administrative tools can be considered where they add genuine value, with privacy, accuracy, transparency and professional oversight planned carefully."],
  ],
  cta: {
    eyebrow: "Build a learning platform designed for your audience.",
    title: "Turn your learning concept into a structured, scalable product.",
    body: "Tell us about your learners, programmes, teaching model and commercial objectives. We will help define the learner, instructor, organisation and administration experiences required to move forward.",
    href: "mailto:info@webtekdigital.com?subject=E-learning%20app%20development%20enquiry",
  },
};

export default function Page() {
  return <CloneAppTemplate config={config} />;
}
